### ISSUE TITLE
How to configure the loading order of RocketMQListener and Springboot Listener？

### ISSUE THREAD

**Issue by itrickzhang** [apache/rocketmq-spring#100]
I need to consume after loading the listener for spring boot. The configuration annotation @Order is not valid and has been the first to load RocketMQListener. 
![image](https://user-images.githubusercontent.com/23379828/60710076-7588c180-9f44-11e9-82d4-eeabc5fae526.png)

**Comment by fangjian0423** [comment]
I think you could try to use [Spring Cloud Stream](https://spring.io/projects/spring-cloud-stream) to do this.

**Comment by ShannonDing** [comment]
link #107
