### ISSUE TITLE
How to config producer vipChannelEnabled in application.properties ?

### ISSUE THREAD

**Issue by SpinSi** [apache/rocketmq-spring#101]
**Two question**
1 >  How to config producer vipChannelEnabled in application.properties ?
   
2> How to use RocketMQTemplate send msg with implemeted selected queue by myself ? 

Thanks for your replay.

**Comment by fangjian0423** [comment]
for Q1: it is not supported by configuration properties, you could use system property by `com.rocketmq.sendMessageWithVIPChannel` key

for Q2:  refer `RocketMQTemplate#setMessageQueueSelector`
