### ISSUE TITLE
How RocketMQMessageListener Sets Tag?

### ISSUE THREAD

**Issue by zuoanguo** [apache/rocketmq-spring#103]

**Comment by fangjian0423** [comment]
Refer `RocketMQMessageListener#selectorExpression`.

this attribute can be used for `tag` or `sql` subscribe mode, the subscribe mode refer `RocketMQMessageListener#selectorType`.

**Comment by xue2lang** [comment]
@fangjian0423 now the tag not support resolvePlaceholders （eg：selectorExpression=${my.xx.tag} ），the default is * 。 when used，we should implement RocketMQPushConsumerLifecycleListener to set other info。   
RocketMQMessageListener define the property （selectorExpression），but  it doesn't seem to be working friendly now

**Comment by fangjian0423** [comment]
contributors are welcome to support resolvePlaceholders.

`selectorExpression` can work, make sure you use the right way!

**Comment by xue2lang** [comment]
@fangjian0423 i review the source code ；ListenerContainerConfiguration#createRocketMQListenerContainer set instance of RocketMQMessageListener to instance of DefaultRocketMQListenerContainer，then execute the method DefaultRocketMQListenerContainer#initRocketMQPushConsumer 。I cannot find resolvePlaceholders where  be used for the property of selectorExpression

**Comment by fangjian0423** [comment]
> @fangjian0423 i review the source code ；ListenerContainerConfiguration#createRocketMQListenerContainer set instance of RocketMQMessageListener to instance of DefaultRocketMQListenerContainer，then execute the method DefaultRocketMQListenerContainer#initRocketMQPushConsumer 。I cannot find resolvePlaceholders where be used for the property of selectorExpression

It is not supported and welcome to contribute it.

**Comment by liuliuzo** [comment]
@fangjian0423 我的这个pull request 有机会被merge吗？
