### ISSUE TITLE
Unable to support payload with byte[] type in methods with payload such as 'syncSend(String destination, Object payload)'

### ISSUE THREAD

**Issue by lemonzone2010** [apache/rocketmq-spring#104]
Unable to support payload with byte[] type in methods with payload such as 'syncSend(String destination, Object payload)'

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

Try the following code. But message content is changed to `"YWJj"` (a base64 encoded string)
```java
        byte[] valueAsByte = "abc".getBytes();
        rocketMQTemplate.syncSend("xxx", valueAsByte);
```

- What did you expect to see?

the origin bytes:`"abc".getBytes()`

- What did you see instead?

a base64 encoded string:`"YWJj"`

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by ShannonDing** [comment]
link #147 
it will be fixed by #152
