### ISSUE TITLE
Two consumer instances consume the same message, and some messages are not consumed

### ISSUE THREAD

**Issue by whoamigodson** [apache/rocketmq-spring#107]

**Comment by vongosling** [comment]
Please write your questions according to the question template

**Comment by whoamigodson** [comment]
when started two consumer instances consume the same topic message,if two consumer instances is same name,but listen two different port,and some messages are not consumed.

**Comment by whoamigodson** [comment]
class ListenerContainerConfiguration
private void registerContainer(String beanName, Object bean) {
        Class<?> clazz = AopProxyUtils.ultimateTargetClass(bean);

        if (!RocketMQListener.class.isAssignableFrom(bean.getClass())) {
            throw new IllegalStateException(clazz + " is not instance of " + RocketMQListener.class.getName());
        }

        RocketMQMessageListener annotation = clazz.getAnnotation(RocketMQMessageListener.class);
        validate(annotation);

        String containerBeanName = String.format("%s_%s", DefaultRocketMQListenerContainer.class.getName(),
            counter.incrementAndGet());



so,containerBeanName can config by RocketMQMessageListener?

**Comment by whoamigodson** [comment]
In rocketmq-spring,two different consumer process,but client id is same one.how to fix?
clientId                                                                                                                                  192.168.1.11@org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_1 
clientAddr
192.168.1.11:52320

clientId
192.168.1.11@org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_1 	
clientAddr
192.168.1.11:52341

**Comment by RongtongJin** [comment]
@whoamigodson Currently, you can temporarily solve this issue by implementing RocketMQPushConsumerLifecycleListener and setting a unique instanceName in prepareStart. Contributors are welcome to solve this issue.
