### ISSUE TITLE
使用rocketmq-spring-boot-starter单机部署双节点时，存在消费两次的问题

### ISSUE THREAD

**Issue by sxt102400** [apache/rocketmq-spring#116]
我在部署服务时，一台机器部署了两个tomcat节点，由于rocketmq-spring-boot-starter框架重新定义了instanceName， 此时一个consumerGroup中， 两个节点是属于，同ip同instanceName， 导致两个tomcat节点每份节点都消费一次数据。

希望能改进一下这个机制，解决rocketmq-spring-boot-starter框架下，消费者默认配置时，单机双节点消费2次的问题。

**Comment by RongtongJin** [comment]
@sxt102400 Thanks for your advice. Your advice sounds reasonable and welcome to submit a PR to fix this issue.
