### ISSUE TITLE
consumer.subscribe is not valid

### ISSUE THREAD

**Issue by flybalance** [apache/rocketmq-spring#118]
@Override
	public void prepareStart(DefaultMQPushConsumer consumer) {
		try {
//			consumer.subscribe("${rocketmq.marketIndexTask.topic}", 
//                     "${rocketmq.marketIndexTask.marketTagName}");
			consumer.subscribe("${rocketmq.marketIndexTask.topic}", "derived");
			consumer.setConsumeThreadMin(8);
			consumer.setConsumeThreadMax(12);
		} catch (MQClientException exception) {
			logger.error("MQClientException exception =" + exception.getMessage());
		}
	}

I have set the tag type of the subscription, but I will still get messages from other tag types.
Do I still need other settings?

**Comment by RongtongJin** [comment]
You can set filter expression by setting selectorExpression like this：

```@RocketMQMessageListener (topic = “xxx”, selectorExpression = “yyy”, consumerGroup = “zzz”)```

It is not recommended to invoke subscribe again in the prepareStart method. If you subscribe the same topic in this method, the original filter expression will be overwritten.
