### ISSUE TITLE
Profile is not prompted

### ISSUE THREAD

**Issue by yekl** [apache/rocketmq-spring#12]

**Comment by vongosling** [comment]
@yekl please detail your bug report or feature request?

**Comment by yekl** [comment]
> 
> 
> @yekl please detail your bug report or feature request?

Rocketmq configuration items are not prompted when filling out the application.yml configuration file configuration

**Comment by yekl** [comment]
Rocketmq configuration items are not prompted when filling out the application.yml configuration file configuration

> 
> 
> @yekl please detail your bug report or feature request?

**Comment by yekl** [comment]
> 
> 
> @yekl please detail your bug report or feature request?

Rocketmq configuration items are not prompted when filling out the application.yml configuration file configuration
