### ISSUE TITLE
Question about ext info in message header.

### ISSUE THREAD

**Issue by fattan9577** [apache/rocketmq-spring#121]
1、为了异步解耦，把一些操作放在了消息队列中，
但是目前发送消息不能指定header，导致消费消息时丢失header信息，不能完成业务

**Comment by ShannonDing** [comment]
Could you please descript this question more detail?

**Comment by fattan9577** [comment]
您好 我英语不太好 用中文不知道您能理解吗


就是我们的服务在调用接口的时候需要传递自定义header


消费者在消费的时候需要调用其他服务提供的接口，所以我希望在生产消息的时候指定自定义header 这样在消费的时候 直接使用指定的自定义header



------------------ 原始邮件 ------------------
发件人: "dinglei"<notifications@github.com>;
发送时间: 2019年8月20日(星期二) 下午3:10
收件人: "apache/rocketmq-spring"<rocketmq-spring@noreply.github.com>;
抄送: "傻子丁"<349341704@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/rocketmq-spring] Question about ext info in messageheader. (#121)




Could you please descript this question more detail?

**Comment by RongtongJin** [comment]
You can send a message by overloading method like xxxSend(String destination, Message<?> msg, ...), setting headers of msg. for example:
```
Message<?> message = MessageBuilder.withPayload(payload).setHeader(MessageConst.PROPERTY_KEYS, msgId).build();
rocketMQTemplate.send("topic-test", message);
```
Similarly, you can also set the message FLAG, WAIT_STORE_MSG_OK and some other user-defined other header information according to the above method.

Note:

In the case of converting Spring's Message to RocketMQ's Message, to prevent the header information from conflicting with RocketMQ's system properties, the prefix USERS_ was added in front of all header names. So if you want to get a custom message header when consuming, please pass through the key at the beginning of USERS_ in the header.
