### ISSUE TITLE
Suggestion on cosuming message idempotently.

### ISSUE THREAD

**Issue by dongdongzld** [apache/rocketmq-spring#122]
In most cases, we need to de-duplicate messages to achieve idempotency, but the system does not provide any extension points to do this.

**Comment by dongdongzld** [comment]
大部分情况下，我们都需要对消息去重，从而实现幂等，但系统没有提供任何扩展点来做这个事情，虽然可以在
public void onMessage(MessageExt messageExt)
内实现，感觉不太优雅，有大量的重复代码

**Comment by dongdongzld** [comment]
建议RocketMQListener增加一个checkMessage方法

**Comment by dongdongzld** [comment]
![image](https://user-images.githubusercontent.com/3351049/63268517-ebfc3b80-c2c6-11e9-88ba-37b7db92f93e.png)
![image](https://user-images.githubusercontent.com/3351049/63268545-fc141b00-c2c6-11e9-9927-cd1aea7b5959.png)

**Comment by RongtongJin** [comment]
The extension point of idempotent message processing is not considered temporarily.  Users can process idempotent message by themselves in onMessage method.
