### ISSUE TITLE
How to set shardingKey in RocketMQTemplate?

### ISSUE THREAD

**Issue by leizihui** [apache/rocketmq-spring#123]
RocketMQTemplate 如何设置shardingKey

**Comment by RongtongJin** [comment]
@leizihui Setting shardingKey is not supported in RocketMQTemplate yet, but you can set MessageQueueSelector to send ordered messages.
```java
rocketMQTemplate.setMessageQueueSelector(new MessageQueueSelector() {
   public MessageQueue select(List<MessageQueue> mqs, org.apache.rocketmq.common.message.Message msg,
                Object arg) {
                ……
   }
});
```

**Comment by leizihui** [comment]
> @leizihui Setting shardingKey is not supported in RocketMQTemplate yet, but you can set MessageQueueSelector to send ordered messages.
> 
> ```java
> rocketMQTemplate.setMessageQueueSelector(new MessageQueueSelector() {
>    public MessageQueue select(List<MessageQueue> mqs, org.apache.rocketmq.common.message.Message msg,
>                 Object arg) {
>                 ……
>    }
> });
> ```

thanks，understood！
