### ISSUE TITLE
ListenerContainerConfiguration.java set nameServer but RocketMQMessageListener  already have PLACEHOLDER

### ISSUE THREAD

**Issue by liuliuzo** [apache/rocketmq-spring#128]
version: Master

ListenerContainerConfiguration.java 的130-131行
 String nameServer = environment.resolvePlaceholders(annotation.nameServer());
nameServer = StringUtils.isEmpty(nameServer) ? rocketMQProperties.getNameServer() : nameServer;

@interface RocketMQMessageListener 中已经有了 
String NAME_SERVER_PLACEHOLDER = "${rocketmq.name-server:}";
  /**
     * The property of "name-server".
     */
String nameServer() default NAME_SERVER_PLACEHOLDER;

再从rocketMQProperties中拿一次是不是重复了。

**Comment by RongtongJin** [comment]
如果用户在注解中设置了无效（Empty）的namServer，则从rocketMQProperties中获取，否则从注解中获取。
