### ISSUE TITLE
Once consumers restarted, all the previously subscribed messages are resent ?

### ISSUE THREAD

**Issue by yanglin2000168** [apache/rocketmq-spring#13]
@RocketMQMessageListener(topic = RocketmqTopics.EMAIL, consumerGroup = RocketmqTopics.EMAIL_CONSUMER)

public class EmailRocketMQServiceImpl implements RocketMQListener<MailParam> {

     public void onMessage(String msgId,MailParam mailParam) {

     }
   
}

**Comment by walking98** [comment]
This behavior should be caused by the broker config, it does not relate with Spring client. 
这个应该与broker端的消费位点更新的配置有关系，不是客户端的行为，只要onMessage没有抛出异常，就会返回 ConsumeConcurrentlyStatus.CONSUME_SUCCESS

不使用spring, 直接使用RocketMQPushConsumer API是否也能重现这个问题？

**Comment by walking98** [comment]
@yanglin2000168

**Comment by yanglin2000168** [comment]
这个问题只出现在把阿里的emc上，而本里测试环境不能重现发自我的华为手机-------- 原始邮件 --------主题：Re: [apache/rocketmq-spring] 在阿里云服务器部署rocketmq 4.2.0用于生产环境，每一次重启consumer所在服务器，出现将之前订阅过消息全部重新发送一次 (#13)发件人：Kevin Wang 收件人：apache/rocketmq-spring 抄送：yanglin2000168 ,Author This behavior should be caused by the broker config, it does not relate with Spring client.

这个应该与broker端的消费位点更新的配置有关系，不是客户端的行为，只要onMessage没有抛出异常，就会返回 ConsumeConcurrentlyStatus.CONSUME_SUCCESS

不使用spring, 直接使用RocketMQPushConsumer API是否也能重现这个问题？
