### ISSUE TITLE
on right,in Maven projects,some dependencies is red

### ISSUE THREAD

**Issue by chinaTLJ** [apache/rocketmq-spring#135]
有的依懒拉不下来是什么原因，报红

**Comment by RongtongJin** [comment]
Could you please descript this question more detail? What are the dependencies you can't pull?

**Comment by chinaTLJ** [comment]
就是下了这个项目，
![image](https://user-images.githubusercontent.com/17891721/63988448-eac0df00-cb0e-11e9-924e-4ca3bdeb373c.png)这个东西拉不下来，要我自己添加它的依懒才行

**Comment by RongtongJin** [comment]
This is just a normal netty dependency, probably caused by your network problem.
