### ISSUE TITLE
selectorExpression support placeholder

### ISSUE THREAD

**Issue by qwer120158285** [apache/rocketmq-spring#142]
RocketMQMessageListener的topic、consumerGroup使用占位符都解析了，单单selectorExpression未解析，是有意而为之还是漏了啊？

**Comment by yinjunonly** [comment]
emmm，可能因为这个是用来表示表达式的

**Comment by vongosling** [comment]
@qwer120158285 selector这块暂时不支持占位符。如果大家有需求，可以开一个issue提。
