### ISSUE TITLE
整合问题

### ISSUE THREAD

**Issue by 18710103279** [apache/rocketmq-spring#146]
请问这个2.0.3版本可以在使用了springboot1.5.4的项目中引入吗？  如果不能，在不升级1.5.4的情况下，有什么其他解决方案吗？

**Comment by RongtongJin** [comment]
RocketMQ-spring does not support spring boot version of 1.5.x considering the surpport of spring in the future, maybe you can use [original rocketmq](https://github.com/apache/rocketmq) in your spring boot project.

**Comment by vongosling** [comment]
@18710103279 rocketmq spring is not designed to support 1.x. you could upgrade your version to the latest version according to this doc, https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide
