### ISSUE TITLE
FEATURE REQUEST support namespace

### ISSUE THREAD

**Issue by Shellbye** [apache/rocketmq-spring#149]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Support namespace

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
Different environment need namespace to support

**Comment by RongtongJin** [comment]
It should be implemented on the rocketmq side instead of rocketmq-spring.
