### ISSUE TITLE
BUG: Infinite loop in DefaultRocketMQListenerContainer

### ISSUE THREAD

**Issue by shepherdviolet** [apache/rocketmq-spring#151]
https://github.com/apache/rocketmq-spring/blob/908ea4812192b36789c46d230b2fa61f51f3c867/rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/support/DefaultRocketMQListenerContainer.java#L392-L395

If there is more than one inheritance from RocketMQListener, there will be an infinite loop. For example, MyRocketMQListener --extend--> BaseRocketMQListener --extend--> AbstractRocketMQListener --implement--> RocketMQListener.

Suggestion: Adjust the method getMessageType. 

Our way to get actual type of generic:

```text
    private static Type[] getGenericTypesOfInterface(Class clazz, Class targetGenericInterface) {
        Type matchedGenericInterface = null;
        while (clazz != null) {
            Type[] genericInterfaces = clazz.getGenericInterfaces();
            if (genericInterfaces != null) {
                for (Type genericInterface : genericInterfaces) {
                    if (genericInterface instanceof ParameterizedType && targetGenericInterface.equals(((ParameterizedType) genericInterface).getRawType())) {
                        matchedGenericInterface = genericInterface;
                        break;
                    }
                }
            }
            clazz = clazz.getSuperclass();
        }
        if (matchedGenericInterface == null) {
            return null;
        }
        return ((ParameterizedType) matchedGenericInterface).getActualTypeArguments();
    }
```

**Comment by RongtongJin** [comment]
It's indeed a bug. Could you please submit a PR to fix it ?

**Comment by shepherdviolet** [comment]
When I am free, I will submit a PR, (*￣︶￣)

**Comment by shepherdviolet** [comment]
> It's indeed a bug. Could you please submit a PR to fix it ?

When I am free, I will submit a PR, (*￣︶￣)

**Comment by zongtanghu** [comment]
This issue can assign to @zhangjidi2016.And firstly, this issue can assign to me!

**Comment by chenxubiao** [comment]
请问现在支持这种继承写法吗

AbstractRocketMQListener<T> implement  RocketMQListener<T>

MyMsgListener extend AbstractRocketMQListener<Msg>
