### ISSUE TITLE
 The producer group[SALES_PAY_NOTIFY] has been created before,

### ISSUE THREAD

**Issue by qiaojiang2** [apache/rocketmq-spring#153]
rg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionListenerImpl' defined in file [/Users/qiaojiang/dev-tools/workspace/mafengwo_workspace/pay-notify/pay-notify-provider/target/classes/com/mafengwo/pay/notify/provider/listener/TransactionListenerImpl.class]: Initialization of bean failed; nested exception is org.springframework.messaging.MessagingException: The producer group[SALES_PAY_NOTIFY] has been created before, specify another name please.
See http://rocketmq.apache.org/docs/faq/ for further details.; nested exception is org.apache.rocketmq.client.exception.MQClientException: The producer group[SALES_PAY_NOTIFY] has been created before, specify another name please.
See http://rocketmq.apache.org/docs/faq/ for further details.

**Comment by RongtongJin** [comment]
The reason for the exception is that you had already registered a producer named SALES_PAY_NOTIFY to instance. Two producer groups of the same name cannot be registered to the same instance.  It would be better if you can provide more detailed information.
