### ISSUE TITLE
@RocketMQTransactionListener没有nameServer属性，报错？

### ISSUE THREAD

**Issue by shmily2038** [apache/rocketmq-spring#156]
使用2.0.3版本
![image](https://user-images.githubusercontent.com/16485682/66698299-58b41500-ed0f-11e9-9143-f7251ddd2032.png)
使用扩展的类，进行分布式事务消息发送
![image](https://user-images.githubusercontent.com/16485682/66698314-9749cf80-ed0f-11e9-98fd-d2693a4afcbc.png)
虽然定义类分布式事务的监听器，并加注解和实现接口，但还是报错了。
![image](https://user-images.githubusercontent.com/16485682/66698432-aa10d400-ed10-11e9-9767-9c269e90ca9e.png)
不是明明已经有了？

这个注解是否还要指定对应的namserver？  但是@RocketMQTransactionListener这个注解里没有对应的nameServer这个属性。

**Comment by RongtongJin** [comment]
Error have nothing to do with the @RocketMQTransactionListener annotation having no namesever attribute . It seems that extRocketMQTemplate can not send transaction messages yet. It must use rocketMQTemplate to send transaction messages.

**Comment by shmily2038** [comment]
What can extRocketMQTemplate do? When can transactional messaging be supported?

**Comment by vongosling** [comment]
You can look for the parts of "How do I create more than one RocketMQTemplate with a different name-server or other specific properties?" in the README
