### ISSUE TITLE
Maven dependency cannot be pulled

### ISSUE THREAD

**Issue by caibi123** [apache/rocketmq-spring#17]
Maven dependency cannot be pulled

**Comment by caibi123** [comment]
<dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.0.1-SNAPSHOT</version>
        </dependency>

**Comment by windhc** [comment]
Still not pushed to the maven center?

**Comment by Ouyangan** [comment]
#5

**Comment by Ouyangan** [comment]
#5 
you can view this issue

**Comment by walking98** [comment]
we are pushing the jar into maven central repo in 2.0.1, it will be available in the week. stay tuned.

**Comment by windhc** [comment]
Zzzz...

**Comment by vongosling** [comment]
Maven repository could download now.
