### ISSUE TITLE
Why don't you take a TAG from the Header

### ISSUE THREAD

**Issue by zainzhoucom** [apache/rocketmq-spring#176]
`MessageBuilder.withPayload(new Model()).setHeader(RocketMQHeaders.TAGS,"test.tag").build()`

RocketMQUtil.getAndWrapMessage

`//Why is that?`
`String[] tempArr = destination.split(":", 2);`
`String topic = tempArr[0];`
`String tags = "";`
` if (tempArr.length > 1) {`
`          tags = tempArr[1];`
`  }`
`Message rocketMsg = new Message(topic, tags, payloads);`
             

`//Why not`
`Object tag = headers.get(RocketMQHeaders.TAGS);`
` if(!StringUtils.isEmpty(tag)){`
`    rocketMsg.setTags(tag.toString());`
`  }`
`Object keys = headers.get(RocketMQHeaders.KEYS);`

**Comment by RongtongJin** [comment]
Some method,  such as `asyncSend(String destination, Object payload, SendCallback sendCallback, long timeout) `, users will not  build spring messages, they cannot place tag. So we put the tag in destination.
