### ISSUE TITLE
 has been created before in unit test

### ISSUE THREAD

**Issue by Croyson** [apache/rocketmq-spring#180]
单元测试情况下报错，如何解决
The producer group[xxxx] has been created before, specify another name please.

**Comment by RongtongJin** [comment]
Which unit test？According to the information you gave, this is caused by multiple consumers with the same group name defined in the same instance.

**Comment by Croyson** [comment]
springboot  with  'maven test'！ Container started multiple times，And then the mistake happened

**Comment by RongtongJin** [comment]
I tried `mvn test` in my environment, all tests passed. Could you please provide more detailed log？

**Comment by Croyson** [comment]
使用@MockBean,springboot被多次启动，所以有重复报错，现在跑mvn test的时候把RocketMQAutoConfiguration 排除掉就好了
