### ISSUE TITLE
use "@RocketMQMessageListener" listen two topics, only one topic  can get message trace

### ISSUE THREAD

**Issue by leoxchang** [apache/rocketmq-spring#182]
I used "@ RocketMQMessageListener" listen two topics, that from one nameSrv;only one topic  can get message trace. I debug the rocketmq client source,I see that "AsyncTraceDispatcher.start" method throws MQClientException,because the traceProducer has bean created,the "MQ-AsyncTraceDispatcher-Thread-" thread can not start. so one DefaultMQPushConsumer can not send trace message. 

当使用”@RocketMQMessageListener“ 监听通过服务地址的topic时，只有其中的一个topic是可以查询到消息轨迹的，我debug源码发现"AsyncTraceDispatcher.start"这个方法抛出了MQClientException，原因是traceProducer 已经被创建过了，所以"MQ-AsyncTraceDispatcher-Thread" 线程没有被启动，导致其中的一个DefaultMQPushConsumer没法发送trace消息。

**Comment by RongtongJin** [comment]
There is a same [issue](https://github.com/apache/rocketmq/issues/1619) in rocketmq main repo.
