### ISSUE TITLE
use rocketmq-spring，springboot JacksonAutoConfiguration doesn't work

### ISSUE THREAD

**Issue by jiangctry** [apache/rocketmq-spring#187]
import rocketmq-spring， springboot load RocketMQAutoConfiguration and JacksonFallbackConfiguration create bean ObjectMapper.  JacksonAutoConfiguration cannot be load and jackson properties doesn't work

**Comment by RongtongJin** [comment]
Could you give more details? Because in my enviroment, there is no such issue, so I want to know how to reproduce it?

**Comment by vongosling** [comment]
@jiangctry any other details for helping locate your problem?

**Comment by fangqyou** [comment]
> reproduce
I want to make the fields that are null not serializable，So I implemented this function like this：
 in appilication.yml 
spring.jackson:
  default-property-inclusion: non_null
  serialization.write-dates-as-timestamps: true

use rocketmq-spring ,this config  lose effectiveness |  
-- | --
