### ISSUE TITLE
tags is invalid

### ISSUE THREAD

**Issue by lexiLiu** [apache/rocketmq-spring#195]
代码中设置了TAGS，但是发消息时TAGS是无效的。
`Message<Order> message = MessageBuilder
                .withPayload(order)
                // keys
                .setHeader(MessageConst.PROPERTY_KEYS, id))
                // tags
                .setHeader(MessageConst.PROPERTY_TAGS, MqConfig.EventTagEnum.TAG_ORDER_CREATE.tag)
                .build();
        rocketMQTemplate.asyncSend(MqConfig.orderEvent, message, new SendCallback() {});`

我跟踪了源码，发现`RocketMQUtil.convertToRocketMessage`中有一段代码过滤了tags，如下：
`headers.entrySet().stream()
                .filter(entry -> !Objects.equals(entry.getKey(), "FLAG")
                    && !Objects.equals(entry.getKey(), "WAIT_STORE_MSG_OK")) // exclude "FLAG", "WAIT_STORE_MSG_OK"
                .forEach(entry -> {
                    if (!MessageConst.STRING_HASH_SET.contains(entry.getKey())) {
                        rocketMsg.putUserProperty(entry.getKey(), String.valueOf(entry.getValue()));
                    }
                });`

`(!MessageConst.STRING_HASH_SET.contains(entry.getKey()))`，这个判断没有理解，我猜想是不是这个判断多了 `!`，过滤我设置的TAGS

**Comment by RongtongJin** [comment]
When you use rocketMQTemplate to send a message, set the destination of the message by setting the destination parameter of the send method. The destination format is topicName:tagName, : Precedes the name of the topic, followed by the tags name. As shown below,
https://github.com/apache/rocketmq-spring/blob/1bea434f5436b14cae35fb9f9b90737a474ade44/rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java#L106-L110.
Currently, setting tag through header is not supported. If you have a need for this, please tell me.
