### ISSUE TITLE
After the introduction of rocketmq-spring-boot-starter in the project, the related configuration of Jackson was invalidated

### ISSUE THREAD

**Issue by liyueforever** [apache/rocketmq-spring#196]
I use springboot and springcloud to build the project. After introducing the dependency of rocketmq-spring-boot-starter in the project, all the custom jackson configuration classes are not working properly.
The Jackson configuration class is placed in the jar package and initialized in the project using the import annotation.
For example, the following configuration class is normal before the introduction of rocketmq-spring-boot-starter.
![image](https://user-images.githubusercontent.com/46366155/70516780-8502db00-1b72-11ea-8c99-06977e9e04af.png)
This question may be the same as #187

My version information : 
springboot : 2.0.6.RELEASE
springcloud  : Finchley.SR3
rocketmq-spring-boot-starter : 2.0.4
jdk : 1.8.0.91

**Comment by RongtongJin** [comment]
@liyueforever , Is it a compile error or runtime error? Is there any error message?

**Comment by liyueforever** [comment]
> @liyueforever , Is it a compile error or runtime error? Is there any error message?

No error message，just the Jackson configuration class does not take effect.
I seem to have found a solution. After deleting the configuration of JacksonFallbackConfiguration in the code of rocket-spring-boot, there will be no problem.

**Comment by RongtongJin** [comment]
@liyueforever Could you have a try with latest master branch code? It has removed JacksonFallbackConfiguration in the code.

**Comment by liyueforever** [comment]
> @liyueforever Could you have a try with latest master branch code? It has removed JacksonFallbackConfiguration in the code.

I downloaded and used the 2.0.5-SNAPSHOT version, this version can solve my problem
