### ISSUE TITLE
扩展数据源发送事务消息

### ISSUE THREAD

**Issue by gagado** [apache/rocketmq-spring#202]
1、扩展的数据源创建的是默认的producer，不能发送事务消息

**Comment by RongtongJin** [comment]
ExtRocketMQTemplate does not support sending transactional messages temporarily.

**Comment by gagado** [comment]
好的，谢谢。这块以后会完善吗？ 是否有计划加上发送事务消息。

**Comment by gagado** [comment]
> ExtRocketMQTemplate does not support sending transactional messages temporarily.

好的。谢谢，这块以后会完善吗? 是否有计划加上发送事务性消息。不好意思，打扰了。

**Comment by RongtongJin** [comment]
会完善的。近期会提交PR修复这个问题，可以关注下。
