### ISSUE TITLE
Support Spring boot 1.5.18 ?

### ISSUE THREAD

**Issue by xiaolongyuan** [apache/rocketmq-spring#21]

**Comment by walking98** [comment]
It should be supported, please modify the [version](https://github.com/apache/rocketmq-spring/blob/8e1466e75f77998ddbfd7e1571f75ad55eca4cc3/rocketmq-spring-boot-parent/pom.xml#L39) to 1.5.18 and try it. @xiaolongyuan

**Comment by xiaolongyuan** [comment]
Not supported.

```
private void registerContainer(String beanName, Object bean) {
        Class<?> clazz = AopUtils.getTargetClass(bean);
        if (!RocketMQListener.class.isAssignableFrom(bean.getClass())) {
            throw new IllegalStateException(clazz + " is not instance of " + RocketMQListener.class.getName());
        } else {
            RocketMQMessageListener annotation = (RocketMQMessageListener)clazz.getAnnotation(RocketMQMessageListener.class);
            this.validate(annotation);
            String containerBeanName = String.format("%s_%s", DefaultRocketMQListenerContainer.class.getName(), this.counter.incrementAndGet());
            GenericApplicationContext genericApplicationContext = (GenericApplicationContext)this.applicationContext;
            genericApplicationContext.registerBean(containerBeanName, DefaultRocketMQListenerContainer.class, () -> {
                return this.createRocketMQListenerContainer(bean, annotation);
            }, new BeanDefinitionCustomizer[0]);
            DefaultRocketMQListenerContainer container = (DefaultRocketMQListenerContainer)genericApplicationContext.getBean(containerBeanName, DefaultRocketMQListenerContainer.class);
            if (!container.isRunning()) {
                try {
                    container.start();
                } catch (Exception var9) {
                    log.error("Started container failed. {}", container, var9);
                    throw new RuntimeException(var9);
                }
            }

            log.info("Register the listener to container, listenerBeanName:{}, containerBeanName:{}", beanName, containerBeanName);
        }
    }
```

genericApplicationContext.registerBean is Spring 5.x

**Comment by xiaolongyuan** [comment]
@walking98

**Comment by xiaolongyuan** [comment]
![image](https://user-images.githubusercontent.com/3142363/50391358-b8403480-077e-11e9-872a-b727ccf7ec0c.png)

**Comment by walking98** [comment]
It can work in my test after change to<spring.boot.version>1.5.18.RELEASE</spring.boot.version> rocketmq-spring-boot-parent/pom.xml 

1. changed the spring.boot.version to 1.5.18.RELEASE
2. cd rocketmq-spring/ 
3. mvn clean install -Dmaven.test.skip
4. run the samples and verify:
    cd rocketmq-spring-samples\
    mvn clean package
    

@xiaolongyuan

**Comment by xiaolongyuan** [comment]
![image](https://user-images.githubusercontent.com/3142363/50415424-e2185a80-0855-11e9-8d5e-924e60e9716b.png)

spring boot 1.5.x依赖为 4.3.x

**Comment by xiaolongyuan** [comment]
@walking98

**Comment by walking98** [comment]
The official release version supports Spring boot 2.x + Spring 5.X, the latest spring version.

The issue title should be "support Spring 4.x + Spring 1.X", this is a back-forward compatible issue. we need some investigation and figure out how to support both.

**Comment by walking98** [comment]
Here is a potential fix: https://github.com/apache/rocketmq-spring/pull/25 

But it might not be checked in due to the official release will support Spring-boot 2.X only. 

@xiaolongyuan

**Comment by xiaolongyuan** [comment]
@walking98 Why  support Spring-boot 2.X only ?

**Comment by 237chenhao** [comment]
@xiaolongyuan 
1.
![image](https://user-images.githubusercontent.com/12470925/50460859-a6e06d80-09b4-11e9-956d-73d0785a72bb.png)
2.
![image](https://user-images.githubusercontent.com/12470925/50460881-c8415980-09b4-11e9-848f-fb61d68e7609.png)
3.
![image](https://user-images.githubusercontent.com/12470925/50460914-17878a00-09b5-11e9-865f-d6857c04f0f8.png)

我本地运行demo是OK没有发现明显报错.

**Comment by zhao41654828** [comment]
> @xiaolongyuan
> 1.
> ![image](https://user-images.githubusercontent.com/12470925/50460859-a6e06d80-09b4-11e9-956d-73d0785a72bb.png)
> 2.
> ![image](https://user-images.githubusercontent.com/12470925/50460881-c8415980-09b4-11e9-848f-fb61d68e7609.png)
> 3.
> ![image](https://user-images.githubusercontent.com/12470925/50460914-17878a00-09b5-11e9-865f-d6857c04f0f8.png)
> 
> 我本地运行demo是OK没有发现明显报错.

我用你这个改动，mvn clean package 编译就有报错.

我也觉得@walking98 应该支持低版本的spring boot 哇

不然很多使用低版本的springboot的服务，都得为了引入你这个jar包，然后去升级版本，升级版本可能会带来更多不可预料的问题

**Comment by xiaolongyuan** [comment]
@zhao41654828 我现在用的是 pull里面的那个方案 后面准备全面升级至spring boot 2了

**Comment by walking98** [comment]
Hope this discussion will help you understand why we no longer support spring boot 1.x
https://github.com/apache/rocketmq-spring/pull/25

**Comment by zhao41654828** [comment]
> @zhao41654828 我现在用的是 pull里面的那个方案 后面准备全面升级至spring boot 2了

嗯，我也尝试切spring boot 2 吧
