### ISSUE TITLE
A template can only bind one group at present. How to implement multiple instances of rocketmq template？

### ISSUE THREAD

**Issue by niutd777** [apache/rocketmq-spring#211]
目前在使用阿里云的rocketMQ,但是官方对于事务消息group有限制 “[事务消息的 Group ID 不能与其他类型消息的 Group ID 共用](https://help.aliyun.com/document_detail/43348.html?spm=a2c4g.11174283.6.553.6c56537cQl76uJ)”（注意事项第一条）。现在使用场景需要使用多种消息类型，不知道针对这种场景需要如何配置？想着使用ExtRocketMQTemplate仅支持事务消息，RocketMQTemplate支持其他类型消息，但使用@ExtRocketMQTemplateConfiguration报错提示nameServer property is same with global property， please use the default RocketMQTemplate! 

针对如上场景需要如何配置，请指教

**Comment by RongtongJin** [comment]
I think we should remove the limitation that ExtRocketMQTemplate can not keep the same nameserver as RocketMQTemplate. I will submit a PR to solve this issue.

**Comment by niutd777** [comment]
When released the new version ?

**Comment by niutd777** [comment]
> I think we should remove the limitation that ExtRocketMQTemplate can not keep the same nameserver as RocketMQTemplate. I will submit a PR to solve this issue.

When released the new version ?

**Comment by RongtongJin** [comment]
> > I think we should remove the limitation that ExtRocketMQTemplate can not keep the same nameserver as RocketMQTemplate. I will submit a PR to solve this issue.
> 
> When released the new version ?

The new version will be release ASAP. If you use rocketmq-spring 2.0.3 or 2.0.4, you can set transaction producer group name different  from rocketmqTemplate group name.
