### ISSUE TITLE
when MessageModel.BROADCASTING ,so error #106

### ISSUE THREAD

**Issue by romantictravel01** [apache/rocketmq-spring#217]
https://github.com/apache/rocketmq-spring/issues/106
不明白为什么关闭,最新的版本是2.0.4,我遇到了同样的问题

https://github.com/apache/rocketmq-spring/issues/106
![image](https://user-images.githubusercontent.com/59325449/71552071-502acb00-2a30-11ea-80b0-f5536bd654f0.png)

![image](https://user-images.githubusercontent.com/59325449/71552069-4739f980-2a30-11ea-9f52-26971aba0104.png)

**Comment by romantictravel** [comment]
offsets.json.bak 乱码 乱码 乱码

**Comment by RongtongJin** [comment]
There is a similar [issue](https://github.com/apache/rocketmq/issues/1498) you can refer to.

**Comment by 6westboy9** [comment]
> #106
> 不明白为什么关闭,最新的版本是2.0.4,我遇到了同样的问题
> 
> #106
> ![image](https://user-images.githubusercontent.com/59325449/71552071-502acb00-2a30-11ea-80b0-f5536bd654f0.png)
> 
> ![image](https://user-images.githubusercontent.com/59325449/71552069-4739f980-2a30-11ea-9f52-26971aba0104.png)

解决问题了吗？没有看到有相应的答复就给关了

**Comment by sdmq** [comment]
分析原因:
package org.apache.rocketmq.client.consumer.store;

public class LocalFileOffsetStore implements OffsetStore {
..................
public LocalFileOffsetStore(MQClientInstance mQClientFactory, String groupName) {
this.mQClientFactory = mQClientFactory;
this.groupName = groupName;
this.storePath = LOCAL_OFFSET_STORE_DIR + File.separator + this.mQClientFactory.getClientId() + File.separator + this.groupName + File.separator + "offsets.json";
}

加载本地json 时出错,

解决办法:

根据LOCAL_OFFSET_STORE_DIR 这个目录 找到目录 一块删除了就可以
以windows为例:
C:\Users{登录用户}.rocketmq_offsets
删除这个目录下所有文件即可
