### ISSUE TITLE
when spring proxy bean will repeat name with "scopeTarget" bean to make some consumer

### ISSUE THREAD

**Issue by forfuns** [apache/rocketmq-spring#218]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

when I use @RefreshScope( with alibaba nacos ) to make hot deploy properties features,`rocketmq-spring` will find some bean name with `scopeTarget.` , that will make some name for one bean,and register replace consumer with clientId like "IP@PID" , that is not work for `rocketmq` 4.6.0.

**FEATURE REQUEST**
filter bean without spring proxy 

this fix on PR#210

**Comment by forfuns** [comment]
@RongtongJin hello,any idea with this enhancement of next version deploy time ?

**Comment by RongtongJin** [comment]
@forfuns RocketMQ-Spring 2.1.0 will release ASAP. It depends on when the  [pr](https://github.com/apache/rocketmq-spring/pulls) are merged to master, especially the pr of request-reply.
