### ISSUE TITLE
required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.

### ISSUE THREAD

**Issue by shuowang97** [apache/rocketmq-spring#223]
**I recently used rocketMQ to achieve message system in my project, but after I downloaded and added these two dependencies in below:**
 
         <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
            <version>4.3.2</version>
        </dependency>

**And I also added spring.rocketmq.producer.group & spring.rocketmq.nameServer in my application.properties file.** 

The whole project cannot run and there is an error in below:**

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'rocketMQTemplate' in 'RocketMQAutoConfiguration' not loaded because @ConditionalOnProperty (spring.rocketmq.nameServer) did not find property 'nameServer'

**When I get into RocketMQAutoConfiguration file:
   It shows errors in DefaultMQProducer and it cannot construct defaultMQProducer in this snippet**

producer = new DefaultMQProducer(groupName, new AclClientRPCHook(new 
                SessionCredentials(ak, sk)),
                rocketMQProperties.getProducer().isEnableMsgTrace(),
                rocketMQProperties.getProducer().getCustomizedTraceTopic());
            producer.setVipChannelEnabled(false);

I am a beginner in RocketMQ and hope you can help out. Thanks in advance.

**Comment by RongtongJin** [comment]
You only need to add rocketmq-spring-boot-starter dependency. Do not add rocketmq-client dependency. In addition, it is recommended that you upgrade the version of the rocketmq-spring-boot-starter dependency and refer to the examples in the samples package.
