### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by myzf** [apache/rocketmq-spring#231]
**AsyncTraceDispatcher dispatcher = new AsyncTraceDispatcher(customizedTraceTopic, isEnableAcl ? new AclClientRPCHook(new SessionCredentials(ak, sk)) : null);**

### This line of code is missing two parameters, hope to add in time, otherwise the project can not compile

**producer.getDefaultMQProducerImpl()**
### The code is obsolete

**Comment by RongtongJin** [comment]
I'm confused because I can compile successfully.
