### ISSUE TITLE
how do i return ACK_SUCESS to NameServer?

### ISSUE THREAD

**Issue by huffmant** [apache/rocketmq-spring#235]
onMessage is a return void method,how do i return if ack_success or ack_fail to nameServer so it can resend a message?

**Comment by RongtongJin** [comment]
By default, Consume_Success is returned. If an exception is thrown in onMessage method, RECONSUME_LATER will be returned. So if you want resend a message, just throw exception.

**Comment by bigyShot** [comment]
> By default, Consume_Success is returned. If an exception is thrown in onMessage method, RECONSUME_LATER will be returned. So if you want resend a message, just throw exception.

But in onMessage(),it can't throw exception,it must be catched

**Comment by lixianli1987** [comment]
yes, it should move,but i dont know why
![AAORB}FO}(DOO`0)N~{ZIH7](https://github.com/user-attachments/assets/287d4054-69a1-4822-b39a-a732cc7a0ed2)
