### ISSUE TITLE
How to control the flow per second?

### ISSUE THREAD

**Issue by Wilson-He** [apache/rocketmq-spring#240]
I want to control consumption efficiency by configuration file(application.yml) or @RocketMQMessageListener params，such as I want to pull 1000 message per second, but I didn't find corresponding parameter configuration.
Should I custom a DefaultMQPushConsumer and then set "pullThresholdForTopic" and "pullInterval"?

**Comment by RongtongJin** [comment]
RocketMQ do not provide parameters that directly limit the consumption rate of clients.
But you can set "pullThresholdForTopic" or "pullInterval"  by implementing RocketMQPushConsumerLifecycleListener interface in rocketmq-spring.  You can refer to article 8 of wiki [FAQ](https://github.com/apache/rocketmq-spring/wiki/FAQ).
