### ISSUE TITLE
Due Diligence for RocketMQ Request-Reply

### ISSUE THREAD

**Issue by duhenglucky** [apache/rocketmq-spring#249]
## Due Diligence

RocketMQ Request-Reply is an important part of rocketmq ecology, which aims to help developers quickly build micro-service based on RocketMQ. In order to better understand the use of the RocketMQ Request-Reply and continue to optimize it. Here, we sincerely invite you to take a minute to feedback on your usage scenario.

## What we expect from you
Pls. submit a comment in this issue to include the following information:
• your company, school or organization
• your country and city
• your contact info, such as email, WeChat and twitter (optional).
• usage scenario
• expectations(optional)

You can refer to the following sample answer for the format:
```
* Organization: XX Company
* Location: Seoul, South Korea
* Contact: foobar@gmail.org
* Version: v4.6.0(rocketmq) or v2.1.0(rocketmq-spring)
* Usage scenario: RocketMQ Request is used in Multi-segment communication, etc., with the server scale of 3W+ message queues on 200+ brokers  and the client scale of 5000+ 4core 16g virtual machines
* Expectations(optional): Support for consuming batched messages
```
Thanks again for your participation!
Apache RocketMQ Community

## 聆听你的声音
RocketMQ Request-Reply是RocketMQ生态的重要部分，它帮助开发者利用RocketMQ快速构建微服务。为了更好的了解RocketMQ Request Reply的使用情况，并对它其进行持续优化。在这里，我们诚恳的邀请您花费1分钟的时间来反馈一下您的使用场景。

## 我们期待您能提供
一条评论, 评论内容包括但不限于:
• 您所在公司、学校或组织
• 您所在的国家与城市
• 您的联系方式: 邮箱、微信、Twitter账号 (为了更好地保持联系，建议您留下联系方式)
• 您将Apache RocketMQ Request-Reply用于哪些业务场景，使用规模如何
• 您对Apache RocketMQ Request-Reply未来发展有什么期望？

您可以参考下面的样例来提供您的信息：
```
* 公司：XX有限公司
* 地点：韩国首尔
* 联系方式：foobar@gmail.com
* 版本：v4.6.0(rocketmq) or v2.1.0(rocketmq-spring)
* 场景与规模：将RocketMQ Request Reply用于微服务构建，跨网段调用等核心场景，目前服务端大约200+台broker，3W+队列数，客户端规模5000+台 4core 16g 虚拟机。
* 期望（可选）：希望后续版本能在消费端增加批量消费支持
```

非常感谢您的参与
Apache RocketMQ Community

**Comment by qqeasonchen** [comment]
* 公司：国内某银行
* 地点：深圳
* 联系方式：qqeasonchen@apache.com
* 版本：v4.6.0(rocketmq) 
* 场景与规模：将RocketMQ Request Reply用于微服务构建，跨网段调用等核心场景。
* 期望（可选）：希望能将这个特性集成到Dubbo中，将消息服务化

**Comment by 2259289435** [comment]
公司：物流公司
地点：长沙
联系方式：2259289435@qq.com
版本：v4.6.0
场景与规模：将RocketMQ Request Reply用于微服务构建，跨网段调用等核心场景。
* 期望（可选）：
1.消费端没有启动，发送消息的时候可选支持是直接报错还是等待超时
2.处理时可以针对不同的tag使用不同的线程池

**Comment by ifplusor** [comment]
* 公司：北京智慧星光信息技术有限公司
* 地点：中国北京
* 联系方式：ywhjames@hotmail.com
* 版本：v4.6.0(rocketmq) or re_dev(rocketmq-client-cpp)
* 场景与规模：用于计算服务调用，方便资源伸缩与管理。

**Comment by troubleshooting1** [comment]
公司：个人
地点：杭州
联系方式：867904553@qq.com
版本：v4.4.0
场景与规模：个人学习使用
期望：希望后续版本能在消费端增加批量消费支持
