### ISSUE TITLE
@ExtRocketMQTemplateConfiguration(value="xxxx")  exception

### ISSUE THREAD

**Issue by kider** [apache/rocketmq-spring#251]
rocketmq-spring-boot-starter-version:2.1.0

use:
@ExtRocketMQTemplateConfiguration(value='xxx')

@Resource(name = "xxx")
 private RocketMQTemplate extRocketMQTemplate;

it always throws 'Bean {} has been used in Spring Application Context, " +
                    "please check the @ExtRocketMQTemplateConfiguration' exception， only if not set value

**Comment by RongtongJin** [comment]
@kider It seems that the bean with the name 'xxx' already exists, you can change the name.

**Comment by kider** [comment]
> @kider It seems that the bean with the name 'xxx' already exists, you can change the name.
it does't work to change the name . i found the same bean is himself when i debug

**Comment by wz2cool** [comment]
meet same issue
