### ISSUE TITLE
@RocketMQTransactionListener can definition multiple implement class？

### ISSUE THREAD

**Issue by gagado** [apache/rocketmq-spring#253]
In my project, have multiple transaction message.
so, i definition multiple RocketMQLocalTransactionListener implement class;
one:

@Component
@RocketMQTransactionListener
public class OneMesssageListener implements RocketMQLocalTransactionListener {

@Override
    public RocketMQLocalTransactionState executeLocalTransaction(Message msg, Object arg) {
}
}

two:

@Component
@RocketMQTransactionListener
public class TwoMesssageListener implements RocketMQLocalTransactionListener {

@Override
    public RocketMQLocalTransactionState executeLocalTransaction(Message msg, Object arg) {
}
}

but,have a error:
rocketMQTemplate already exists RocketMQLocalTransactionListener;

i want know, if In one project， i have multiple transaction message.
What should i do？

thanks...

**Comment by RongtongJin** [comment]
You can use ExtRocketMQTemplate and specify the bean name in RocketMQTransactionListener annotation.
You can refer to
https://github.com/apache/rocketmq-spring/blob/1464698a8b03d5700d41efe9258c33acf14b8e81/rocketmq-spring-boot-samples/rocketmq-produce-demo/src/main/java/org/apache/rocketmq/samples/springboot/ProducerApplication.java#L277-L291

**Comment by gagado** [comment]
@RongtongJin Thanks your answer, But in my project, only one RocketMQTemplate is defined and only one data source is used. ExtRocketMQTemplate should represent the situation of multiple data sources. When I use multiple rocketmq clusters in a project, it is my understanding. is it wrong? Thank you.

**Comment by diwayou** [comment]
same problem, this is caused by rocketmq new client, merge local transaction execute and check listener, but it make code too difficult, i like the old callback way, how to solve this problem, i think you can route the message by type/key or else in the RocketMQLocalTransactionListener implementation, any one have a better solution?

**Comment by Xuchengen** [comment]
看样子需要自己做一个基于`topic:tag`路由分发来解决这个问题。
