### ISSUE TITLE
Sendandreceive method error

### ISSUE THREAD

**Issue by Alvinnlee** [apache/rocketmq-spring#256]
version：2.1.0
springboot: 2.1.6.RELEASE

org.apache.rocketmq.client.exception.RequestTimeoutException: CODE: 10006  DESC: send request message to <string-topic> OK, but wait reply message timeout, 10000 ms.

But the news can be consumed, just reported as wrong

**Comment by RongtongJin** [comment]
It has been fixed.

**Comment by wangpo1991** [comment]
version：rocketmq-client-4.7.1
springboot: 2.3.11.RELEASE
error:org.springframework.messaging.MessagingException: CODE: 10006  DESC: send request message to <topic_XXX> OK, but wait reply message timeout, 3000 ms.; nested exception is org.apache.rocketmq.client.exception.RequestTimeoutException: CODE: 10006  DESC: send request message to <topic_XXX> OK, but wait reply message timeout, 3000 ms.

But the news can be consumed, just reported as wrong

**Comment by wangpo1991** [comment]
@RongtongJin help,help,help
