### ISSUE TITLE
如何连接阿里云的rocketmq产品

### ISSUE THREAD

**Issue by inotgaoshou** [apache/rocketmq-spring#267]
1.支持使用阿里云的rocketmq产品吗？name-server 是http协议 tpc协议。
https://help.aliyun.com/document_detail/44711.html?spm=a2c4g.11186623.6.589.7ba5626506tfJl

**Comment by inotgaoshou** [comment]
已解决。

**Comment by vongosling** [comment]
@inotgaoshou 可以分享下你的经验，方便后续类似问题的同学少走弯路：-）
