### ISSUE TITLE
Support SpringBoot 1

### ISSUE THREAD

**Issue by iapplejohn** [apache/rocketmq-spring#280]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
    rocketmq-spring project doesn't support SpringBoot 1 (Spring 4), but most of applications in my corporation are based on SpringBoot 1.

2. Provide any additional detail on your proposed use case for this feature.
    We could support SpringBoot 1.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
    We'd like to use rocketmq-spring to simplify the usage of rocketmq, and it would take a lot of time to upgrade to SpringBoot 2.

**Comment by RongtongJin** [comment]
Since SpringBoot 1 will no longer be maintained later, RocketMQ-Spring has no plan to support SpringBoot 1.

**Comment by iapplejohn** [comment]
From my perspective, there are plenty of applications running with SpringBoot 1, since rocketmq supports JDK 6, it is not ok to support SpringBoot 1 (Spring 4) ?
