### ISSUE TITLE
Max consumer timeout(consumeTimeout) in the class of RocketMQMessageListener is incorrect

### ISSUE THREAD

**Issue by UPC-FUZI** [apache/rocketmq-spring#287]
> the unit of consumeTimeout shoud be in minutes

**[definition]** RocketMQMessageListener.class
`
// Max consumer timeout, default 30s.

long consumeTimeout() default 30000L;
`

**[invoking]** ConsumeMessageConcurrentlyService.class
`
defaultMQPushConsumer.getConsumeTimeout() * 60 * 1000
`

**Comment by RongtongJin** [comment]
Which version are you using? If I remember correctly this problem should have been fixed.

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
