### ISSUE TITLE
The  versions in samples are not same

### ISSUE THREAD

**Issue by WreathCrystal** [apache/rocketmq-spring#314]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
    I want to compile the samples project.

- What did you expect to see?
   I expected no errors occur.

- What did you see instead?
   There is no rocketmq-spring-boot-samples-2.1.1-SNAPSHOT.jar found.   

2. Please tell us about your environment:
    Please see the screeshots.  Version difference can be found 
![1606286272(1)](https://user-images.githubusercontent.com/26850311/100192100-45243780-2f2c-11eb-8216-2f1656c40f38.png)
![1606286309(1)](https://user-images.githubusercontent.com/26850311/100192114-481f2800-2f2c-11eb-8b30-d64098f14612.png)

.

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by RongtongJin** [comment]
Good catch！Could you submit a pull request to fix the issue?

**Comment by WreathCrystal** [comment]
Sure

**Comment by WreathCrystal** [comment]
> Good catch！Could you submit a pull request to fix the issue?

When I compile samples on my pc  in order to fix the issue,   errors occur as below
![checkstyle-failed](https://user-images.githubusercontent.com/26850311/100198501-e57f5980-2f36-11eb-9661-d60ce601bc2f.png)

I think ,   I  need solve this problem before summitting  my request. But I  don not know how to checkstyle sucessfully.
