### ISSUE TITLE
org.apache.rocketmq.common.message.Message.body=“ok”, then changed to b2s=, why?

### ISSUE THREAD

**Issue by WreathCrystal** [apache/rocketmq-spring#315]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
   
- What did you do (The steps to reproduce)?
   1)  org.apache.rocketmq.common.message.Message m = new Message() 
   2)  m.setBody("ok".getBytes(RemotingHelper.DEFAULT_CHARSET));
   3)  String jsonString =  com.alibaba.fastjson.JSONObject.toJSONString(m);
   4)  System.out.println(jsonString)
   5)  output:   {"body":"b2s="}
    

- What did you expect to see?
   I want to see ,  output: {"body":"ok"}

- What did you see instead?
   output:  {"body":"b2s="}

2. Please tell us about your environment:
    rocket-spring-2.1.2 

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
    If I  passed  m  via  rocketMQTemplate.syncSend("test",m),   rocketmq broker will receive the message like {"body":"b2s="}

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by RongtongJin** [comment]
I tried to reproduce using the latest master branch, but this issue did not reproduce in my environment. Could you describe the reproduction steps in more detail? Or just post the code

**Comment by RongtongJin** [comment]
I will close the Issue first, but please feel free to reopen it if you have any other issues.
