### ISSUE TITLE
在消费端我怎么给broker回执消费结果？

### ISSUE THREAD

**Issue by tp19900212** [apache/rocketmq-spring#321]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by RongtongJin** [comment]
RocketMQ-Spring中若不抛出异常则默认消费成功（CONSUME_SUCCESS），若抛出异常则消费失败（RECONSUME_LATER）。

**Comment by lixianli1987** [comment]
> RocketMQ-Spring中若不抛出异常则默认消费成功（CONSUME_SUCCESS），若抛出异常则消费失败（RECONSUME_LATER）。

抛出错误后，会重试消费，offset依然会移动
