### ISSUE TITLE
Question about not cosuming

### ISSUE THREAD

**Issue by shf675** [apache/rocketmq-spring#348]
使用rocketmq-spring-boot-starter时工程中只写了一个消费者，使用了topicA，可以正常消费，然后又增加了一个消费者，随便写了一个topicB，则都不消费了。
![image](https://user-images.githubusercontent.com/7691856/107140583-f2202500-695d-11eb-96e6-99d35f7ee5ea.png)
![Uploading image.png…]()

**Comment by RongtongJin** [comment]
另一张图无法看到，可以贴下详细的代码？另外两个消费者是否是同一个group，如果是同一个group的话这样操作会有订阅关系不一致的问题，参考[wiki第三条](https://github.com/apache/rocketmq-spring/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by wbzj1110** [comment]
建议 读取一下consumer的 offset，之前我们遇到过很多消费问题 都是同一个group的offset问题。
建议 基于rocketmq-console-ng做一下内部的  方便排查问题 列表一出来问题就好排查了
![image](https://user-images.githubusercontent.com/11921135/108318173-5793d180-71fa-11eb-841c-489a95f4dd58.png)
