### ISSUE TITLE
2.2.0 can not consummer in aliyun

### ISSUE THREAD

**Issue by l343765828** [apache/rocketmq-spring#356]
@Service
@RocketMQMessageListener(topic = "*",consumerGroup = "*",accessChannel = "CLOUD",
accessKey = "*",secretKey = "*",selectorExpression = "*",
nameServer = "http://*.cn-beijing.mq-internal.aliyuncs.com:8080")
public class DeviceStatusTest implements RocketMQListener<MessageExt> {

    @Override
    public void onMessage(MessageExt messageExt) {
        System.out.println("接受设备消息");
    }
}

当使用内网地址的时候 收不到消息 在阿里云的控制台也显示离线 当使用公网地址的时候 一切正常 但是 参照阿里云官方文档在main里写 内网地址又在线了 并且可以收到消息了：
    private static RPCHook getAclRPCHook() {
        return new AclClientRPCHook(new SessionCredentials("*", "*"));
    }
    public static void main(String[] args) {
        //设置为您在阿里云消息队列RocketMQ版控制台上创建的GID, 以及替换为您阿里云账号的AccessKey ID和AccessKey Secret。
        DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("*",
                getAclRPCHook(), new AllocateMessageQueueAveragely());
        //设置为阿里云消息队列RocketMQ版实例的接入点。
        consumer.setNamesrvAddr("http://*.cn-beijing.mq-internal.aliyuncs.com:8080");
        //阿里云上消息轨迹需要设置为CLOUD方式。
        consumer.setAccessChannel(AccessChannel.CLOUD);
        // 设置为您在阿里云消息队列RocketMQ版控制台上创建的Topic。
        try {
            consumer.subscribe("*", "*");
        } catch (MQClientException e) {
            e.printStackTrace();
        }
        consumer.registerMessageListener(new MessageListenerConcurrently() {
            @Override
            public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,
                                                            ConsumeConcurrentlyContext context) {
                System.out.printf("Receive New Messages: %s %n", msgs);
                return ConsumeConcurrentlyStatus.CONSUME_SUCCESS;
            }
        });
        try {
            consumer.start();
        } catch (MQClientException e) {
            e.printStackTrace();
        }
        SpringApplication.run(MessageConsumerApplication.class, args);
    }

**Comment by l343765828** [comment]
@RongtongJin

**Comment by l343765828** [comment]
我知道问题了 在配置文件里 配置完name-server 就不行了 配置哪个地址 哪个地址的group不行

**Comment by RongtongJin** [comment]
> 我知道问题了 在配置文件里 配置完name-server 就不行了 配置哪个地址 哪个地址的group不行

没有复现出来，能详细描述一下复现的方法和配置吗？

**Comment by l343765828** [comment]
application.yml:
rocketmq:
  #mq的nameserver地址
  name-server: "http://a.cn-beijing.mq-internal.aliyuncs.com:8080"
  access-channel: "CLOUD"
  consumer:
    access-key: "*"
    secret-key: "*"
注解：
@RocketMQMessageListener(topic = "devicestatus",consumerGroup = "GID_devicestatus",nameServer = "b")
配置文件是一个地址 注解是一个地址 我这边就是配置文件写哪个 哪个就连不上 
比如配置文件写a 注解写b地址就能连b 其他注解不写地址的 连不上a 后来我又试 配置文件写a 注解写a 我也连不上a 我拿阿里公网和内网的tcp测的
现在我用2.0.4版本的 就没这问题 怎么写都能连
@RongtongJin

**Comment by RongtongJin** [comment]
> application.yml:
> rocketmq:
> #mq的nameserver地址
> name-server: "http://a.cn-beijing.mq-internal.aliyuncs.com:8080"
> access-channel: "CLOUD"
> consumer:
> access-key: "_" secret-key: "_"
> 注解：
> @RocketMQMessageListener(topic = "devicestatus",consumerGroup = "GID_devicestatus",nameServer = "b")
> 配置文件是一个地址 注解是一个地址 我这边就是配置文件写哪个 哪个就连不上
> 比如配置文件写a 注解写b地址就能连b 其他注解不写地址的 连不上a 后来我又试 配置文件写a 注解写a 我也连不上a 我拿阿里公网和内网的tcp测的
> 现在我用2.0.4版本的 就没这问题 怎么写都能连
> @RongtongJin

仍然没有复现

**Comment by l343765828** [comment]
我springboot版本是2.1.12.RELEASE

**Comment by l343765828** [comment]
@RongtongJin

**Comment by ShannonDing** [comment]
link #353

**Comment by ShannonDing** [comment]
> application.yml:
> rocketmq:
> #mq的nameserver地址
> name-server: "http://a.cn-beijing.mq-internal.aliyuncs.com:8080"
> access-channel: "CLOUD"
> consumer:
> access-key: "_" secret-key: "_"
> 注解：
> @RocketMQMessageListener(topic = "devicestatus",consumerGroup = "GID_devicestatus",nameServer = "b")
> 配置文件是一个地址 注解是一个地址 我这边就是配置文件写哪个 哪个就连不上
> 比如配置文件写a 注解写b地址就能连b 其他注解不写地址的 连不上a 后来我又试 配置文件写a 注解写a 我也连不上a 我拿阿里公网和内网的tcp测的
> 现在我用2.0.4版本的 就没这问题 怎么写都能连
> @RongtongJin

客户端日志里面有没有链接nameserver的日志和报错信息。

**Comment by l343765828** [comment]
说到日志 我也想问下 日志存哪了 没找到呢 客户端是放docker里了 docker的系统是centos windows的我知道了 centos的就一直没找到

**Comment by l343765828** [comment]
@ShannonDing

**Comment by RongtongJin** [comment]
> 说到日志 我也想问下 日志存哪了 没找到呢 客户端是放docker里了 docker的系统是centos windows的我知道了 centos的就一直没找到

rocketmq客户端的日志在主目录的logs/rocketmqlogs/rocketmq_client.log下面，看下spring boot的日志，重点看下“running container: DefaultRocketMQListenerContainer{ xxxx }”这类日志，consumer的配置是否正确？

**Comment by LiYeLin** [comment]
老哥们 这个template的生产者怎么链接的阿里云啊 用ExtRocketMQTemplateConfiguration吗？#361  @l343765828 @RongtongJin
