### ISSUE TITLE
关于消费者优雅上下线怎么做呢

### ISSUE THREAD

**Issue by xiangyang-gao** [apache/rocketmq-spring#360]
如题，使用rocketmq-spring，消费者是否可以进行优雅上下线？

**Comment by xiangyang-gao** [comment]
在停服时，关闭当前机器的消费者连接

**Comment by RongtongJin** [comment]
程序若不是异常关闭（kill -9）,则程序结束时会自动优雅下线。

**Comment by xiangyang-gao** [comment]
> 程序若不是异常关闭（kill -9）,则程序结束时会自动优雅下线。

大佬，不要着急关闭嘛。还有个问题请教下
                DefaultRocketMQListenerContainer container = (DefaultRocketMQListenerContainer)genericApplicationContext.getBean(containerBeanName, DefaultRocketMQListenerContainer.class);

我是不是可以for循环 直接控制获取 DefaultRocketMQListenerContainer。进行stop可以么
