### ISSUE TITLE
我就想知道怎么接入阿里云的RocketMQ

### ISSUE THREAD

**Issue by LiYeLin** [apache/rocketmq-spring#361]
使用template接入了我们现在的测试环境的开源rocketMq 现在想接入阿里这边的社区版本的mq ，所以怎么接入呢？
文档没有丝毫提及 我很困惑 ，#356 在这里面我看到似乎是有这个能力提供的 ，但是那里面只有消费者的写法，生产者怎么生产消息发到阿里上呢？是要像文档里面10那个Ext吗？
_我知道这不是issue的正确用法，但是文档和demo中都没有提及，而且互联网上这个的资料较少 sorry_

**Comment by l343765828** [comment]
阿里云的文档里有社区版接入的方法 直接给客服留个工单 然后客服给你发下链接 社区版只是配置和延时消息需要改下 剩下的都一样

**Comment by l343765828** [comment]
我现在一直用的是2.0.4 用最新版的消费者一直不在线 具体也没查

**Comment by LiYeLin** [comment]
> 阿里云的文档里有社区版接入的方法 直接给客服留个工单 然后客服给你发下链接 社区版只是配置和延时消息需要改下 剩下的都一样

我已经找到了阿里云社区版本接入方法的文档了，但是阿里的接入文档中和demo中给的都是使用apacheRocketMQ的原生api，我想像你一样 使用RocketMQTemplate接入阿里云社区版本 ，请问您怎么用template的api ，实现的能连接上阿里云 的producer？
![image.png](https://i.loli.net/2021/04/15/27mfYNFI3KsxAZl.png)

**Comment by LiYeLin** [comment]
> 阿里云的文档里有社区版接入的方法 直接给客服留个工单 然后客服给你发下链接 社区版只是配置和延时消息需要改下 剩下的都一样

感谢老哥回复
