### ISSUE TITLE
The response results of rocketmqtemplate and defaultmqproducer sendstatus are inconsistent

### ISSUE THREAD

**Issue by Bin2020** [apache/rocketmq-spring#365]
broker 1主1从同步双写，从broker宕机，发送同步消息。RocketMQTemplate应答SEND_OK，DefaultMQProducer应答SLAVE_NOT_AVAILABLE，为什么

```
SendResult sendResult = rocketMQTemplate.syncSend("testTopic", "test");
System.out.println(sendResult.getSendStatus()); // SEND_OK
DefaultMQProducer producer = new TransactionMQProducer("my-group2");
producer.setNamesrvAddr("127.0.0.1:9876");
producer.start();

org.apache.rocketmq.common.message.Message msg = new org.apache.rocketmq.common.message.Message("testTopic", "test".getBytes(StandardCharsets.UTF_8));
SendResult sendResult2 = producer.send(msg);
System.out.println(sendResult2.getSendStatus()); // SLAVE_NOT_AVAILABLE
```

**Comment by Bin2020** [comment]
在org.apache.rocketmq.spring.support.RocketMQUtil#getAndWrapMessage方法下，WAIT_STORE_MSG_OK默认为false，但是设计上应该是想默认true的，是BUG吧。
```
Object waitStoreMsgOkObj = headers.getOrDefault("WAIT_STORE_MSG_OK", "true");
rocketMsg.setWaitStoreMsgOK(Boolean.TRUE.equals(waitStoreMsgOkObj)); // Boolean.TRUE.equals("true") always false
```

**Comment by RongtongJin** [comment]
> 在org.apache.rocketmq.spring.support.RocketMQUtil#getAndWrapMessage方法下，WAIT_STORE_MSG_OK默认为false，但是设计上应该是想默认true的，是BUG吧。
> 
> ```
> Object waitStoreMsgOkObj = headers.getOrDefault("WAIT_STORE_MSG_OK", "true");
> rocketMsg.setWaitStoreMsgOK(Boolean.TRUE.equals(waitStoreMsgOkObj)); // Boolean.TRUE.equals("true") always false
> ```

这确实是个bug，有兴趣提交一个pr来修复它吗？
