### ISSUE TITLE
Would you have a plan to support one listener to consumer more topics recently?

### ISSUE THREAD

**Issue by lwanqiang** [apache/rocketmq-spring#37]
i hava many similar topics, i wanna to comsumer them in same listener ,how can i do for this ..

**Comment by walking98** [comment]
good proposal, maybe we can enhance it with 

public void onMessage(String message, String topic) { ...}

welcome anybody to contribute for this enhancement :-)

**Comment by walking98** [comment]
After further investigation, I feel it is difficult to implement due to one Consumer Listener will use a Pull Consumer which subscribes only a single topic defined  in the Listener at the instantiation stage.
