### ISSUE TITLE
Transaction messages is not triggered

### ISSUE THREAD

**Issue by White-S** [apache/rocketmq-spring#375]
The checkLocalTransaction method of TransactionListener implemented when using MQ transaction messages is not triggered

**Comment by chaooo** [comment]
+1

**Comment by zhangjidi2016** [comment]
In my tests with version 2.2.0, the checkLocalTransaction method can work.

![image](https://user-images.githubusercontent.com/18254437/129335734-15bdff55-e677-4512-ac7d-a92c8592a8fc.png)
