### ISSUE TITLE
生产者和消费者关闭消息轨迹

### ISSUE THREAD

**Issue by Phoebus888** [apache/rocketmq-spring#380]
开关参数(enableMsgTrace)来实现消息轨迹是否开启,这个插件是否可以支持  我看下一个版本默认就是false  但是现在生产出现了问题   是否能代码关闭

**Comment by RongtongJin** [comment]
在客户端直接enableMsgTrace设置为false就可以了，这可以从源头上制止消息轨迹得发送。

服务端设置traceOn为false，删除轨迹默认topic(RMQ_SYS_TRACE_TOPIC)也可以尝试
