### ISSUE TITLE
Ali cloud shows no consumption ?

### ISSUE THREAD

**Issue by cn-core** [apache/rocketmq-spring#393]
Ali Cloud conducts news consumption track inquiry, Consumed messages still show not consumed

Project integration rocketmq-spring-boot-starter:2.2.1

![image](https://user-images.githubusercontent.com/30290251/133378073-7e1ac1be-179b-445b-8f1e-0761d61f4806.png)

**Comment by RongtongJin** [comment]
需要设置accessChannel为cloud

**Comment by RongtongJin** [comment]
实际被消费了吗？只是消息轨迹不显示？

**Comment by cn-core** [comment]
> 真的被消费了？只是消息轨迹不显示？

消费者的确消费了, 官方文档有解释说可能是版本兼容问题. 感觉商业版的好多属性rocketmq-spring-boot-starter并未兼容(感觉, 并未查看过源码), 后依赖了官方提供的 Client 一切正常.

谢谢...

**Comment by RongtongJin** [comment]
> > 真的被消费了？只是消息轨迹不显示？
> 
> 消费者的确消费了, 官方文档有解释说可能是版本兼容问题. 感觉商业版的好多属性rocketmq-spring-boot-starter并未兼容(感觉, 并未查看过源码), 后依赖了官方提供的 Client 一切正常.
> 
> 谢谢...

都是兼容的，但和商业版配置项命名上有区别。消息轨迹可以参考：https://github.com/apache/rocketmq-spring/wiki/%E6%B6%88%E6%81%AF%E8%BD%A8%E8%BF%B9
