### ISSUE TITLE
Same group, different selectorExpression , dose it only the later could work?

### ISSUE THREAD

**Issue by Jenyow** [apache/rocketmq-spring#409]
## 版本
2.2.1

## 问题描述
1. 生产者向同一主题：myTopic 的 tag1、tag2 分别发送消息 
2. 在消费者应用中分别使用 @RocketMQMessageListener(topic = "myTopic", consumerGroup = "${spring.application.name}", selectorExpression = "tag1") 、@RocketMQMessageListener(topic = "myTopic", consumerGroup = "${spring.application.name}", selectorExpression = "tag2") 类注解声明消费服务类
3. 只有 1 个可以消费消息，另外一个永远消费不了消息

## 分析
当 topic 、consumerGroup 相同，selectorExpression 不同，启动时后被初始化的 consumer 能消费信息；如果 consumerGroup 的值不同，则都可以消费信息；

## 疑问
是否在同一应用中使用 @RocketMQMessageListener 声明多个消费服务类时， consumerGroup 的值是否一定要不一样？本来是想表达同一消费者组消费不同标签的消息。如果 consumerGroup  的值要求不一样，那意思就变成了，不同消费者组消费不同的标签了。这是否是一个 bug？

**Comment by vongosling** [comment]
目前订阅关系是设计成这样的语义的

**Comment by Jenyow** [comment]
@vongosling 你好。对于微服务来说，一般不是一个微服务就是一个消费者组吗？一个消费者组内根据不同的标签处理不同的逻辑，这个想法是否有问题？如果在同一个消费者类里根据标签写一堆判断，那代码就太丑陋了。这个是RocketMQ本身的原因限制了设计，还是 rocketmq-spring-boot-starter 的设计如此？后面是否考虑支持？
