### ISSUE TITLE
Problems about the keys of message header conversion

### ISSUE THREAD

**Issue by fangjian0423** [apache/rocketmq-spring#41]
Spring messaging/integration provide some annotations or interfaces like `@Header`, `SimpleSequenceSizeReleaseStrategy` to get value from Spring Message Header or handle aggregator messages.

But now the keys in  Spring Message Header has been changed by RocketMQ message header conversion.

For example:

I set `index` key in Spring Message Header, it will be converted to `USERS_index` when convert to RocketMQ Message from Spring Message.

It will converted to `PROPERTIES` key(This is a Map, then get by `USERS_index` key ) when convert back to Spring Message from RocketMQ Message.

So is it better to use raw key in rocketmq user property header and add `rocketmq` prefix in non user property header in message header conversion?

**Comment by walking98** [comment]
sounds reasonable, adding prefix for rocketmq specific properties. It will be great if you would like to enhance it.

**Comment by fangjian0423** [comment]
Adding another example:

If I set `index` key in spring message header, the `condition` should write `headers['PROPERTIES']['USERS_index']=='1'`.

![image](https://user-images.githubusercontent.com/5254035/53626710-72ea2880-3c41-11e9-88f0-2a91028ed48d.png)

I think the better way is using `headers['index']=='1'`.
