### ISSUE TITLE
Some questions about RocketMQLocalTransactionListener.

### ISSUE THREAD

**Issue by ahaha-vip** [apache/rocketmq-spring#414]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

The question is deserialization of `Message` in `RocketMQLocalTransactionListener#executeLocalTransaction` and `RocketMQLocalTransactionListener#checkLocalTransaction`, I want to get the same data structure as I set, but not so, we have to resolve it ourselves. I think `RocketMQUtil#convertToSpringMessage(org.apache.rocketmq.common.message.Message)`should do this, not the user. This logic already exists `org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer#doConvertMessage`.

```
    public void testSendMessageInTransaction() {
        String destination = "test-topic:test-tag";
        List<String> payload = CollUtil.newArrayList("1", "2");
        Message<List<String>> message = MessageBuilder.withPayload(payload).build();
        rocketMQTemplate.sendMessageInTransaction(destination, message, payload);
    }

    public void testRocketMqLocalTransactionListener() {
        new RocketMQLocalTransactionListener() {

            @Override
            public RocketMQLocalTransactionState executeLocalTransaction(Message msg, Object arg) {
                // Custom parameters.
                // No problem at this step.
                @SuppressWarnings("unchecked")
                List<String> customParams = (List<String>) arg;

                // Message payload.
                //The problem is at this step, I want to get the same data structure as I set, but not so, we have to resolve it ourselves.
                @SuppressWarnings("unchecked")
                List<String> payload = (List<String>)msg.getPayload();

                // Execute something.
                return null;
            }

            @Override
            public RocketMQLocalTransactionState checkLocalTransaction(Message msg) {
                // Check something.
                return null;
            }
        };
    }
```

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by Xuchengen** [comment]
我也比较关心这个问题。

**Comment by ahaha-vip** [comment]
> 我也比较关心这个问题。

@Xuchengen 
后面看了下源码，除非在发送消息时把全限定类名给序列化进去，否则反序列化时不知道具体的类型。要么就是executeLocalTransaction加个TypeReference参数去指定类型。所以目前来看只能我们自己去反序列化处理了。
