### ISSUE TITLE
There is an error in the rocketmq-spring-all-2.2.1 release notes.

### ISSUE THREAD

**Issue by heihaozi** [apache/rocketmq-spring#416]
**BUG REPORT**

There is an error in the [rocketmq-spring-all-2.2.1 release notes](https://github.com/apache/rocketmq-spring/releases/tag/rocketmq-spring-all-2.2.1). As shown below:

![图片](https://user-images.githubusercontent.com/2956927/148341984-ee68849d-0822-4ab0-8cc5-0257aa9c21fd.png)

Here should be [[ISSUE #366]](https://github.com/apache/rocketmq-spring/issues/366) .

**Comment by vongosling** [comment]
Fixed, thanks ~
