### ISSUE TITLE
In broadcast mode, the instance name is too long and the message cannot be consumed.

### ISSUE THREAD

**Issue by heihaozi** [apache/rocketmq-spring#417]
**BUG REPORT**

1. Please describe the issue you observed:

Use broadcast mode to consume, consumers will save offset information locally.

When creating the local offset file, the file path defaults to :

`/${user.home}/.rocketmq_offset/${consumer client id}/${consumer group name}/offsets.json`

![](https://user-images.githubusercontent.com/2956927/148374730-5720a0ae-fb58-49f3-bd47-a31c9b0de886.png)

The consumer client id defaults to :

`${client IP}@${instance name}@${unit name}`

![](https://user-images.githubusercontent.com/2956927/148375127-10e13a1b-aa1d-4fec-bd1d-a2ef24187550.png)

Because the instance name is too long, the offset file creation fails, the message cannot be consumed.

2. Please tell us about your environment:

rocketmq-spring 2.1.1

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

 I am willing to submit a PR!

**Comment by RongtongJin** [comment]
Merged
