### ISSUE TITLE
Can not create topic automatically  

### ISSUE THREAD

**Issue by yiminyangguang520** [apache/rocketmq-spring#42]
when after integrateing with rocketmq-spring-boot-start 2.0.1, the app can not create topic automatically
rocketmq server version is 4.0.0
config file is as follows：
`rocketmq.name-server=***:9876;***:9876`
`rocketmq.producer.group=message-producer-group`
`rocketmq.producer.retry-times-when-send-failed=2`
`rocketmq.producer.retry-times-when-send-async-failed=2`
`rocketmq.producer.send-message-timeout=300000`
`rocketmq.producer.compress-message-body-threshold=4096`
`rocketmq.producer.max-message-size=4194304`
`rocketmq.producer.retry-next-server=true`
`rocketmq.custom.topic=custom-sync-topic`

**Comment by walking98** [comment]
Auto-Create topic is a behavior of server side, please check the related property setting on server side.

**Comment by yiminyangguang520** [comment]
> 
> 
> Auto-Create topic is a behavior of server side, please check the related property setting on server side.

thank for your replay, I found the problem, the rocketmq-spring-boot-start 2.0.1 depends on rocketmq-client 4.3.2, but the server version is 4.3.0, after upgrading the server side, It can create topic automatically, why the new version can not be compatible with the previous version ?

**Comment by walking98** [comment]
please compare your broker conf files between two versions, is possible that you set the autoCreateTopicEnable=false in 4.3.0?  The property is true by default.

**Comment by walkerzhao** [comment]
> please compare your broker conf files between two versions, is possible that you set the autoCreateTopicEnable=false in 4.3.0? The property is true by default.

Agree with u!

Maybe the user can check his conf by this commond to find the property value of autoCreateTopicEnable on the rocket mq server side:
```
walker@test-03:/data/services/rocketmq-all-4.4.0-bin-release/bin$ ./mqbroker -m
2019-04-03 10\:00\:45 INFO main - namesrvAddr=localhost:9876
2019-04-03 10\:00\:45 INFO main - brokerClusterName=DefaultCluster
2019-04-03 10\:00\:45 INFO main - brokerId=0
2019-04-03 10\:00\:45 INFO main - autoCreateTopicEnable=true
```

If I have time, I will redo the situation of @yiminyangguang520 to check his problem.
