### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by XiaoyiPeng** [apache/rocketmq-spring#446]
**BUG REPORT**

1. Please describe the issue you observed:

![image](https://user-images.githubusercontent.com/8653312/162865606-00a4d6dd-fade-4997-8f0f-9fcc4a778577.png)

As shown above, the typo **'halp'** should be **'half'**.

2. Please tell us about your environment:

OS: Windows10
branch: master

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by RongtongJin** [comment]
Merged
