### ISSUE TITLE
Why the consumer in rocketmq-spring choose the DefaultMQPushConsumer (push mode but not pull mode)?

### ISSUE THREAD

**Issue by rztao** [apache/rocketmq-spring#454]
Hi ,

Here is some questions about DefaultMQPullConsumer(pull mode) and  DefaultMQPushConsumer( push mode).   What is the difference between them? and why the consumer in rocketmq-spring choose the DefaultMQPushConsumer (push mode) but not pull mode?

Thanks in advance.

**Comment by panzhi33** [comment]
Are you interested in submitting a PR to support litepull。
