### ISSUE TITLE
Broadcast Mode Problem

### ISSUE THREAD

**Issue by hh13516117509** [apache/rocketmq-spring#458]
When I use RocketMQMessageListener annotation to enable broadcast mode, I find that the local save offset generates a different folder each time, and each folder suffix has a time stamp. After restart, I cannot read the last saved file, so I cannot consume the previously unconsumed data.

**Comment by panzhi33** [comment]
What is the sdk version used?

**Comment by panzhi33** [comment]
Yes, there is such a problem, it will be fixed in the next version

**Comment by hh13516117509** [comment]
ok,ok, thank you very much for your reply

**Comment by zhangjidi2016** [comment]
I will fix this problem later
