### ISSUE TITLE
Can the starter support multi rocketmq server

### ISSUE THREAD

**Issue by jackxu2011** [apache/rocketmq-spring#46]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I can sub message from an rocketmq server and pub to another rocketmq server

2. Provide any additional detail on your proposed use case for this feature.

I want to gather message from client rocketmq(in customer env)  to the center env rocketmq(in aliyun)

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

nice-to-have

**Comment by walking98** [comment]
Pls. try to add the wanted rocketmq client dependency before the spring-boot dependency in the pom.xml, e.g.

            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-client</artifactId>
                <version>${wanted-rocketmq-version}</version>
           </dependency>

            ...
          <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>${rocketmq-spring-boot-starter-version}</version>
        </dependency>

**Comment by jackxu2011** [comment]
I mean can use diffrent name-server with producer and Consumer
like:
```
rocketmq.producer.name-server
rocketmq.consumer.name-server
```

![image](https://user-images.githubusercontent.com/4495830/53937876-63f3f200-40e9-11e9-95ca-3bb315eb4af9.png)

**Comment by walking98** [comment]
Good suggestion. I understand you means the following properties:
rocketmq.name-server (by default)
rocketmq.producer.name-server  (optional, override default)
rocketmq.consumer.name-server  (optional, override default)

we will try to improve this, or is there anybody help on this?

**Comment by zhao41654828** [comment]
> Good suggestion. I understand you means the following properties:
> rocketmq.name-server (by default)
> rocketmq.producer.name-server (optional, override default)
> rocketmq.consumer.name-server (optional, override default)
> 
> we will try to improve this, or is there anybody help on this?

Is there anybody solove it? If no, I will solve it!

I have the same problem, one project use serveral mq server!

**Comment by walking98** [comment]
@zhao41654828 please contribute it if you like. thx!

**Comment by zhao41654828** [comment]
> @zhao41654828 please contribute it if you like. thx!

ok, I will do it as soon as possible.

**Comment by walkerzhao** [comment]
@walking98  Kevin, I have created the pull request to the main master.
Please help to review and give me some sugggestions.

**Comment by walking98** [comment]
This feature has been merged, please try the new code or wait the  coming release 2.0.3
