### ISSUE TITLE
consumerGroup name question

### ISSUE THREAD

**Issue by Dreamroute** [apache/rocketmq-spring#468]
我有个消费者：
```java
@Component
@RocketMQMessageListener(topic = "xxx", consumerGroup = "yyy")
public class MyConsumer implements RocketMQListener<String> {}
```

1. `consumerGroup `的值（上方`yyy`处）只有为：`Consumer1`和`Consumer2`，此消费者才生效，其他任何名字都无法消费消息；
2. `console`报错为`unknow`：
![image](https://user-images.githubusercontent.com/8177677/177069753-251ad054-9baf-457c-a136-2a161b9f99d9.png)
3. 异常信息如下：
![image](https://user-images.githubusercontent.com/8177677/177069851-4a7f541f-9664-4cea-8df9-f60b2d6151fd.png)
4. console的消费者信息（consumer manage）是空的：
![image](https://user-images.githubusercontent.com/8177677/177069977-3bf73627-75d0-441a-980a-b3de569a6524.png)

这个问题给我的感觉有点像是 rocketmq的nameserver或者broker把consumer group限制死了一样，似乎只能使用被限制的那几个名称，而其他名称都不生效一样。

请问：这是什么原因呢？我百思不得其解。

**Comment by panzhi33** [comment]
没有这个限制的，可以提供下rocketmq_clien.log,看下具体原因
