### ISSUE TITLE
RocketMQTemplate类中rocketMQMessageConverter的作用？

### ISSUE THREAD

**Issue by ZJulius** [apache/rocketmq-spring#473]
RocketMQTemplate类里面为什么要定义一个RocketMQMessageConverter rocketMQMessageConverter属性并new了一个RocketMQMessageConverter？他有什么额外的作用吗？
（在RocketMQAutoConfiguration里面通过@Bean将RocketMQTemplate加载到spring容器的时候已经通过setMessageConverter将spring容器中的RocketMQMessageConverter放入）

**Comment by panzhi33** [comment]
This part of the code will be refactored later, and now the configuration is too messy here
