### ISSUE TITLE
How to dynamically configure consumerGroup in @RocketMQMessageListener

### ISSUE THREAD

**Issue by HildaM** [apache/rocketmq-spring#491]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
How to dynamically configure consumerGroup in @RocketMQMessageListener？

3. Provide any additional detail on your proposed use case for this feature.
While I'm using @KafkaListener on my consumer method, I could use aop to dynamically configure consumerGroup. Here is example:
![image](https://user-images.githubusercontent.com/46062705/194698812-a21e88b5-dc4c-4675-a271-a55b158ed9e9.png)
The configuration of consumerGroup is based on my project setting, this can reduce unnessary code.

But while using @RocketMQMessageListener, I notice that the consumerGroup value require it to be fixed. And I look up the document of Rocket-spring and couldn't find any AOP method to dynamically configure consumerGroup .
![image](https://user-images.githubusercontent.com/46062705/194698977-264728a0-2e34-4bdb-9adb-b68c2330e890.png)

5. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
It can reduce lots of unnessary code, Improve efficiency.

**Comment by kosmosr** [comment]
I've code done this future in master branch, and it works the same way in kafka

**Comment by HildaM** [comment]
Could you give me some references about this feature please?



| |
Quan
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月16日 19:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [apache/rocketmq-spring] How to dynamically configure consumerGroup in @RocketMQMessageListener (Issue #491) |

I've code done this future in master branch, and it works the same way in kafka

**Comment by kosmosr** [comment]
> Could you give me some references about this feature please? | | Quan ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年10月16日 19:26 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [apache/rocketmq-spring] How to dynamically configure consumerGroup in @RocketMQMessageListener (Issue #491) | I've code done this future in master branch, and it works the same way in kafka — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

[480](https://github.com/apache/rocketmq-spring/pull/480)

**Comment by HildaM** [comment]
thank you very much



| |
Quan
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月16日 19:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [apache/rocketmq-spring] How to dynamically configure consumerGroup in @RocketMQMessageListener (Issue #491) |

Could you give me some references about this feature please? | | Quan @.*** |
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年10月16日 19:26 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [apache/rocketmq-spring] How to dynamically configure consumerGroup in @RocketMQMessageListener (Issue #491) | I've code done this future in master branch, and it works the same way in kafka — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

480
