### ISSUE TITLE
Jar not found in central repository

### ISSUE THREAD

**Issue by Ouyangan** [apache/rocketmq-spring#5]
pls check

**Comment by walking98** [comment]
Thanks for the reminder, at present, the project is in public review phase, as the README wiki stated, users need to execute "mvn install" to build jar into local maven repo.

we will soon release the stabled version into maven central repo in a couple of weeks. Stay tuned and welcome more suggestion :-)

**Comment by Ouyangan** [comment]
Thanks

**Comment by CharlesSong** [comment]
@vongosling Jar-2.0.1 not fond in central repository or taobao maven repository
