### ISSUE TITLE
RocketmqTemplate does not have a method to send delay messages in version 5.0

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq-spring#506]
Message message = new Message(TOPIC, ("Hello scheduled message " + i).getBytes(StandardCharsets.UTF_8));
            // This message will be delivered to consumer 10 seconds later.
            //message.setDelayTimeSec(10);
            // The effect is the same as the above
            // message.setDelayTimeMs(10_000L);
            // Set the specific delivery time, and the effect is the same as the above
            message.setDeliverTimeMs(System.currentTimeMillis() + 3600_000L);

想实现类似的功能没看到哪个接口支持，只找到了固定延迟级别的接口：
SendResult syncSend(String destination, Message<?> message, long timeout, int delayLevel)

**Comment by RongtongJin** [comment]
> Message message = new Message(TOPIC, ("Hello scheduled message " + i).getBytes(StandardCharsets.UTF_8)); // This message will be delivered to consumer 10 seconds later. //message.setDelayTimeSec(10); // The effect is the same as the above // message.setDelayTimeMs(10_000L); // Set the specific delivery time, and the effect is the same as the above message.setDeliverTimeMs(System.currentTimeMillis() + 3600_000L);
> 
> 想实现类似的功能没看到哪个接口支持，只找到了固定延迟级别的接口： SendResult syncSend(String destination, Message<?> message, long timeout, int delayLevel)

当前RocketMQ-Spring支持到4.x，会尽快适配5.0

**Comment by MartinDai** [comment]
5.0也不支持任意指定延迟时间吧，商业版的才有

**Comment by zhouchunhai** [comment]
@I will resolve it

**Comment by mxsm** [comment]
> 5.0也不支持任意指定延迟时间吧，商业版的才有

5.0版本已经支持
