### ISSUE TITLE
use spring boot 3.0 

### ISSUE THREAD

**Issue by turing1989** [apache/rocketmq-spring#509]
pom
![image](https://user-images.githubusercontent.com/17975927/210044131-7bce151d-cece-4dcf-be2c-8a54664cdbc5.png)

appliction.yml
rocketmq:
  name-server: rocket.smart-change.local:9876
  isVIPChannel: false
  producer:
    group: change-group
    send-message-timeout: 30000

![image](https://user-images.githubusercontent.com/17975927/210044182-83da18db-d8bf-4d4b-9806-5769a2cb6e4a.png)

[then]
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2022-12-30T15:07:39.149+08:00 ERROR 48444 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field rocketMQTemplate in com.future.change.smart.changecloud.TestController required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:59240', transport: 'socket'

Process finished with exit code 1

How can i do it well in Spring boot 3.0.0

**Comment by KouShenhai** [comment]
You need to create a RocketMQTemplate bean.
![image](https://user-images.githubusercontent.com/48756217/210252547-bb704521-4469-4be1-9e85-e95191acb7b3.png)
This is my solution. I hope it can help you

**Comment by turing1989** [comment]
thx
