### ISSUE TITLE
能不能出一个能用的新手文档啊

### ISSUE THREAD

**Issue by lw5885799** [apache/rocketmq-spring#52]
用官网的文档，各种坑，一个接一个应接不暇。这样对新人很不友好啊，求大神出个像样的文档

**Comment by vongosling** [comment]
用官网的文档，指的是spring rocketmq的中文文档吗？对了，下次有问题别再这里提，直接邮件列表吧。

**Comment by lw5885799** [comment]
是rocketmq.apache.org/  的文档，现在是不是不维护了呀？

**Comment by walking98** [comment]
产品下在维护中英文的文档，可以看这里
https://github.com/apache/rocketmq/tree/release-4.5.0/docs

新版rocketmq的release也会随产品输出。
