### ISSUE TITLE
How to debug samples in local IDEA

### ISSUE THREAD

**Issue by joeCarf** [apache/rocketmq-spring#540]
I'd like to debug `rocketmq-produce-demo` and see how RocketMQ-Spring works, but I got errors in my IDEA.
<img width="1404" alt="截屏2023-03-09 10 21 41" src="https://user-images.githubusercontent.com/52153761/223899226-ecf751f8-f9fd-442d-90d7-653ffff3570e.png">
When I run `mvn clean install` in `rocketmq-produce-demo`, it returns 
<img width="809" alt="截屏2023-03-09 10 23 22" src="https://user-images.githubusercontent.com/52153761/223899475-ef7378e2-7f1c-4b36-b1c9-d9784483fc2c.png">
So what should I do if I want to debug these samples?

**Comment by tx-cslearn** [comment]
Do you know what to do? I also have this problem
