### ISSUE TITLE
Can the starter provide support for deserializing generic parameters?

### ISSUE THREAD

**Issue by zhoulinshun** [apache/rocketmq-spring#55]
When I created the following code, there was an exception：
`@Slf4j
@Service
@RocketMQMessageListener(consumerGroup = "abc" ,topic = TopicConstant.test_topic)
public class TestConsumer implements RocketMQListener<TestEvent<String>> {

    @Override
    public void onMessage(TestEvent<String> s) {
        log.info("consumer message:{}", s);
    }
}`

Exception-------
`Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.getMessageType(DefaultRocketMQListenerContainer.java:381)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.afterPropertiesSet(DefaultRocketMQListenerContainer.java:277)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
	... 19 common frames omitted`

**Comment by walking98** [comment]
It should work if change parameter type as TestEvent 
public void onMessage(TestEvent s) { ...}

Referencing to sample code: rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/OrderPaidEventConsumer.java

**Comment by zhoulinshun** [comment]
sorry，My expression is wrong.I want to express the following situation
RocketMQListener<TestEvent<String>>

**Comment by zhoulinshun** [comment]
> It should work if changing parameter type as TestEvent
> public void onMessage(TestEvent s) { ...}
> 
> Referencing to sample code: rocketmq-spring-boot-samples/rocketmq-consume-demo/src/main/java/org/apache/rocketmq/samples/springboot/consumer/OrderPaidEventConsumer.java

sorry，My expression is wrong.I want to express the following situation
`RocketMQListener<TestEvent<String>>`

**Comment by walking98** [comment]
hmm, interesting, it is deserves to investigate and improve.

**Comment by zhoulinshun** [comment]
> hmm, interesting, it is deserves to investigate and improve.
前一段时间在项目中遇到了这个问题， 不过通过改写org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer
已经暂时解决了这个问题，期待你们的下一次更新。

**Comment by walking98** [comment]
嗯，有空可以把你解决的细节给大家共享一下。也有助于我们提高这块代码 :-)

**Comment by caimofei** [comment]
Recently, I tryied solve this problem.
1. My Main idea is use org.springframework.messaging.converter.SmartMessageConverter#fromMessage .This interface define a third parameter called "Object conversionHint".
2. I switch the Definition of DefaultRocketMQListenerContainer#messageType to Type insteadof Class
3. add a "private  MethodParameter onMessageParameter" member  to DefaultRocketMQListenerContainer and init it to indicate the onMessage parameter when afterPropertiesSet() 
4.when doCovertMessage. if the messageType instanceof  ParameterizedType, then call fromMessage with the third parameter(methodParameter). The MappingJackson2MessageConverter can use it to deserialization the message.
