### ISSUE TITLE
why not use this sdk , rocketmq-client-java,i recently use it in springboot project ，and want to know how to connect 4.x client。

### ISSUE THREAD

**Issue by Fate729** [apache/rocketmq-spring#555]
why not use this sdk , rocketmq-client-java,i recently use it in springboot project ，and want to know how to connect 4.x client。

**Comment by 1294566108** [comment]
[rocketmq-clients](https://github.com/apache/rocketmq-clients/tree/master/java)  is the 5.0 client of RocketMQ . Current [rocketmq-spring](https://github.com/apache/rocketmq-spring) only supports the 4.x version of the SDK, and it does not support the SDK version 5.0 for the time being. The task of integrating 5.0 SDK is under development
