### ISSUE TITLE
spring rocketmq 2.2.0 兼容 rocketmq-client 5.0.0版本吗？

### ISSUE THREAD

**Issue by colinchen13** [apache/rocketmq-spring#574]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by colinchen13** [comment]
spring rocketmq 2.2.0 对原生sdk 哪些版本以上兼容？

**Comment by letsky** [comment]
> spring rocketmq 2.2.0 对原生sdk 哪些版本以上兼容？

starter对应的客户端版本
|stater version|rocket client version|
|---|---|
|2.2.0|4.8.0|
|2.2.1| 4.9.1|
|2.2.2| 4.9.3|
|2.2.3| 5.0.0|

**Comment by francisoliverlee** [comment]
> > spring rocketmq 2.2.0 对原生sdk 哪些版本以上兼容？
> 
> starter对应的客户端版本
> 
> stater version	rocket client version
> 2.2.0	4.8.0
> 2.2.1	4.9.1
> 2.2.2	4.9.3
> 2.2.3	5.0.0

rocketmq client version in starters is https://github.com/apache/rocketmq-spring/blob/master/rocketmq-spring-boot-parent/pom.xml#L44C10-L44C18, you can check it
