### ISSUE TITLE
事务消息返回值问题

### ISSUE THREAD

**Issue by Dreamroute** [apache/rocketmq-spring#58]
@Override
    public DemoCommon login(@RequestBody Login login) {
        
        Message<String> msg = MessageBuilder.withPayload("Hello RocketMQ ").setHeader(RocketMQHeaders.KEYS, "KEY_").build();
        TransactionSendResult result = rmt.sendMessageInTransaction("q2", "q2", msg, login);
        System.err.println(result);
        return new DemoCommon();
        
    }

    @RocketMQTransactionListener(txProducerGroup = "q2")
    class Xx implements RocketMQLocalTransactionListener {

        @Override
        public RocketMQLocalTransactionState executeLocalTransaction(Message msg, Object arg) {
            Login login = (Login) arg;
            DemoCommon dc = demoService.selectDemo(login);
            return RocketMQLocalTransactionState.COMMIT;
        }

        @Override
        public RocketMQLocalTransactionState checkLocalTransaction(Message msg) {
            return RocketMQLocalTransactionState.COMMIT;
        }

    }

**请问，这种情况，我想在login方法中获得RocketMQLocalTransactionListener 中返回值DemoCommon，该咋办呢？谢谢。**

**Comment by walking98** [comment]
https://help.aliyun.com/document_detail/43348.html?spm=a2c4g.11186623.6.551.6805208dZP6vaU

How about using a global ConcurrentHashMap<UUID, DemoCommon >(), but bear in mind that executeLocalTransaction() method may execute later than the  login() method. 

BTW, would you please change the issue title with English?
