### ISSUE TITLE
阿里云mq 5.0系列 消息发送失败

### ISSUE THREAD

**Issue by KevinWqs** [apache/rocketmq-spring#594]
<dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
            <version>2.2.3</version>
        </dependency>

阿里云 mq 版本 5.0系列

报错：

org.apache.rocketmq.client.exception.MQClientException: No route info of this topic: imtest1

**Comment by KevinWqs** [comment]
已经解决，需要配置 access-key secret-key

**Comment by miaotaizi** [comment]
> 已经解决，需要配置 access-key secret-key

他这个 access-key 和 secret-key 是指 控制台-实例详情-访问控制-智能身份识别 里面的那个账号密码吗 ?
