### ISSUE TITLE
2.2.3 springboot3.x 启动报错

### ISSUE THREAD

**Issue by bearmr** [apache/rocketmq-spring#599]
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$LegacyResourceElement.<init>(CommonAnnotationBeanPostProcessor.java:698)

The following method did not exist:

    'java.lang.String javax.annotation.Resource.lookup()'

The calling method's class, org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$LegacyResourceElement, was loaded from the following location:

    jar:file:/E:/mavenlib/org/springframework/spring-context/6.0.11/spring-context-6.0.11.jar!/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor$LegacyResourceElement.class

The called method's class, javax.annotation.Resource, is available from the following locations:

    jar:file:/E:/mavenlib/org/apache/tomcat/annotations-api/6.0.53/annotations-api-6.0.53.jar!/javax/annotation/Resource.class

The called method's class hierarchy was loaded from the following locations:

    javax.annotation.Resource: file:/E:/mavenlib/org/apache/tomcat/annotations-api/6.0.53/annotations-api-6.0.53.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$LegacyResourceElement and javax.annotation.Resource

**Comment by shen-hong-wei** [comment]
你可以找到项目中使用@Resource注解的代码部分，删除原有import的引入，引入import jakarta.annotation.Resource;即可

**Comment by shen-hong-wei** [comment]
> 需要修改项目源码吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/rocketmq-spring" ***@***.***&gt;; 发送时间:&nbsp;2023年12月6日(星期三) 下午5:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/rocketmq-spring] 2.2.3 springboot3.x 启动报错 (Issue #599) ***@***.***注解的代码部分，删除原有import的引入，引入import jakarta.annotation.Resource;即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不需要，是你在自己的service中自动注入的时候使用的@resource注解，需要删除对应的import，然后重新引入jakarta.annotation.Resource;jakarta.annotation.Resource;
