### ISSUE TITLE
Release blocker of RocketMQ-Spring 2.3.0

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq-spring#615]
We are preparing to release rocketmq-spring 2.3.0, and the following tasks need to be completed:

- [ ] Fixing security issues in related dependencies

- [ ] Support for rocketmq-v5-client, which requires more detailed testing. @panzhi33

**Comment by leizhiyuan** [comment]
Could this issue and PR be supported in the 2.3.0 version?

https://github.com/apache/rocketmq-spring/pull/617
