### ISSUE TITLE
Make v5 sample logs to output normally

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq-spring#627]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

Make v5 sample logs to output normally

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Needs Info**

Thank you for reporting this issue. The description is brief — to proceed with verification and fix, please provide:
- [ ] RocketMQ Spring version (v5.x tag/commit)
- [ ] Which sample(s) are affected
- [ ] Steps to reproduce the log output issue
- [ ] Expected vs actual log output
- [ ] Relevant configuration (logback/log4j settings)

This will help us verify the issue against the current codebase and propose a targeted fix.

---
*Automated evaluation by @RockteMQ-AI*
