### ISSUE TITLE
Bump rocketmq version to 5.2.0

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq-spring#631]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**FEATURE REQUEST**

Bump rocketmq version to 5.2.0

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `type/enhancement` | Status: **Evaluated**

Bumping the RocketMQ version to 5.2.0 is a standard maintenance enhancement. Keeps the Spring integration aligned with the latest core features and bug fixes.

**Feasibility:** Straightforward version bump.
**Scope:** `pom.xml` dependency version.
**Compatibility:** Should be backward-compatible if 5.2.0 maintains API compatibility with 5.x.

---
*Automated evaluation by github-manager*
