### ISSUE TITLE
Message asynchronously sent failed to retry

### ISSUE THREAD

**Issue by 613lee** [apache/rocketmq-spring#65]
How to set the message asynchronous send failure retries?
I mean, is this feature supported or there is no support plan in the future? If not, I can only implement it myself in the business code.

**Comment by walking98** [comment]
sure, you can try with the following properties in Spring application.properties:

rocketmq.producer.retryTimesWhenSendAsyncFailed=重试次数
rocketmq.producer.sendMessageTimeout=每次超时时间

**Comment by 613lee** [comment]
> 当然，您可以在Spring application.properties中尝试使用以下属性：
> 
> rocketmq.producer.retryTimesWhenSendAsyncFailed =重试次数
> rocketmq.producer.sendMessageTimeout =每次超时时间

I tried setting the following properties but didn't retry sending, why is this?

rocketmq.producer.retryTimesWhenSendAsyncFailed=5
rocketmq.producer.retry-times-when-send-async-failed=5

**Comment by 613lee** [comment]
> sure, you can try with the following properties in Spring application.properties:
> 
> rocketmq.producer.retryTimesWhenSendAsyncFailed=重试次数
> rocketmq.producer.sendMessageTimeout=每次超时时间

I tried setting the following properties but didn't retry sending, why is this?

rocketmq.producer.retryTimesWhenSendAsyncFailed=5
rocketmq.producer.retry-times-when-send-async-failed=5

**Comment by walking98** [comment]
check your app whether there is self-defined bean DefaultMQProducer existing?  

otherwise the default DefaultMQProducer must take those properties effect.

![image](https://user-images.githubusercontent.com/19318111/57213417-54295900-7019-11e9-9b41-f9f09b1bce3d.png)

**Comment by 613lee** [comment]
Thanks, will you also provide broadcasting consume failure retry mechanism in the future?
