### ISSUE TITLE
Dynamic reconfiguration of consumer support

### ISSUE THREAD

**Issue by cnhaicao** [apache/rocketmq-spring#66]
**FEATURE REQUEST**

1. Please describe the feature you are requesting. issue?

The current listenerContainer is a container corresponding to a consumer, but currently it is impossible to implement a consumer dynamic reconfiguration of consumer threads and other configurations that need to rebuild the consumer. After rocketmq consumer.shutdown, new objects must be built. Currently, dynamic configuration dependency implementation is not provided. It is recommended to provide support.

**Comment by walking98** [comment]
do you have a scenario for using the dynamic reconfiguration of consumer ?  @cnhaicao

**Comment by cnhaicao** [comment]
Such reconfiguration scenarios, such as consumer concurrent consumer thread control, access and use of some restricted resources, must limit the consumer's consumption thread, and often require the application to restart concurrent consumer thread modification.

Currently I am using another rockmq starter and then I have extended the implementation of reconfiguring and restarting the consumer.
At present, rocketmq-spring is not easy to expand.

**Comment by vongosling** [comment]
see https://github.com/apache/rocketmq-spring/issues/173
