### ISSUE TITLE
Document typo ?

### ISSUE THREAD

**Issue by l343765828** [apache/rocketmq-spring#67]
这个@RocketMQTransactionListener(transName="test")注解里的参数名称应该是txProducerGroup吧？
rocketMQTemplate.sendMessageInTransaction("test", "test-topic" msg, null);这个msg前面是不是少个逗号？

**Comment by walking98** [comment]
transName 是用来关联发送的事务消息和回查方法的， 所以使用“test”没有问题的； 是少了个逗号。

另外请把这个问题的标题改成英文的。

**Comment by l343765828** [comment]
参数名称应该是txProducerGroup吧？我看你们源码里已经没有transName了
String txProducerGroup() default "rocketmq_transaction_default_global_name";

**Comment by vongosling** [comment]
@l343765828 欢迎提pr来修正你说的问题：-）
