### ISSUE TITLE
Unable to calculate a request signature，Algorithm HmacSHA1 not available

### ISSUE THREAD

**Issue by kangsafe** [apache/rocketmq-spring#68]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
When use ACLEnable=true，it didn't work.
- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:
JDK 1.8,Window 10,Rocket 4.5.0,
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**
The RocketMQ config broker.conf:
aclEnable=true
The plain_acl.yml:
accounts:
- accessKey: pub
  secretKey: 12345678
  whiteRemoteAddress:
  admin: false
  defaultTopicPerm: PUB
  defaultGroupPerm: PUB
  topicPerms:
  - topicA=PUB
  - topicB=PUB
  groupPerms:
  - group-producer1=PUB

- accessKey: sub
  secretKey: 12345678
  whiteRemoteAddress:
  admin: false
  defaultTopicPerm: DENY
  defaultGroupPerm: DENY
  topicPerms:
  - topicA=SUB
  - topicB=SUB
  groupPerms:
  - group-consumer1=SUB

**Comment by walking98** [comment]
It seems related to the JAVA_OPT " -Djava.ext.dirs",  pls. make sure to define this opt as below that will make the sunjce_provider.jar added in CLASSPATH.

 -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext

**Comment by kangsafe** [comment]
Thanks,This solution is Ok.
