### ISSUE TITLE
using getter and setter to get or set  properties

### ISSUE THREAD

**Issue by chenxubiao** [apache/rocketmq-spring#70]
**FEATURE REQUEST**

1. Please use getter and setter instead of annotation.

The current `DefaultRocketMQListenerContainer#rocketMQMessageListener` uses annotation to set properties, which prevents using of custom annotation to override these properties. I would like to know if it is possible to use getter and setter instead of the annotation?

**Comment by vongosling** [comment]
Sorry, I could not figure out what's your meaning. for this project, we have removed lombok's annotation for it' idea unfriendly.
