### ISSUE TITLE
如何同时消费同一个topic下的不同tag消息

### ISSUE THREAD

**Issue by yunfeide** [apache/rocketmq-spring#79]
请问在使用过程中，我在同一个topic下写了多个不同tag的消息，但是在使用时，发现消费端如果同时消费多个tag，接收到消息，如果只消费一个tag，能接收到，是为什么呢？

**Comment by sanzado** [comment]
> 请问在使用过程中，我在同一个topic下写了多个不同tag的消息，但是在使用时，发现消费端如果同时消费多个tag，接收到消息，如果只消费一个tag，能接收到，是为什么呢？

selectorExpression = "TagA || TagB", 试试这样行不行?
