### ISSUE TITLE
RocketMQTemplate method sigure conflict

### ISSUE THREAD

**Issue by yufeng629** [apache/rocketmq-spring#81]
the bellow two method's sigure from RocketMQTemplate are conflict
syncSend(String destination, Object payload, long timeout)
syncSend(String destination, Collection<Message<?>> messages, long timeout)

when i send batch message，i mean to call the syncSend(String destination, Collection<Message<?>> messages, long timeout) method，but in fact，it always call the syncSend(String destination, Object payload, long timeout)

**Comment by walking98** [comment]
![image](https://user-images.githubusercontent.com/19318111/58678611-ef9cb800-8392-11e9-9af8-9cf522d8db32.png)

I have a simple test to verify the two method signatures, it seems not be a problem in runtime. would you please show your syncSend() invocation code? let's have a close look  @yufeng629

**Comment by walking98** [comment]
tried again with RMQTemplate, the issue can be reproduced. need a fix indeed.

**Comment by yufeng629** [comment]
thanks

**Comment by ShannonDing** [comment]
@yufeng629 Could you please fix this issue and create a PR to 2.0.4 version?
