### ISSUE TITLE
RocketMQUtil#addUserProperties can override headers from rocketmq(eg topic,tags,queue id...)

### ISSUE THREAD

**Issue by wangxing-git** [apache/rocketmq-spring#83]
**BUG REPORT**

1. Please describe the issue you observed:
```java
    private static void addUserProperties(Map<String, String> properties, MessageBuilder messageBuilder) {
        if (!CollectionUtils.isEmpty(properties)) {
            properties.forEach((key, val) -> {
                if (!MessageConst.STRING_HASH_SET.contains(key) && !MessageHeaders.ID.equals(key)
                    && !MessageHeaders.TIMESTAMP.equals(key)) {
                    messageBuilder.setHeader(key, val);
                }
            });
        }
    }
```
Here is the judgment that can not override the properties from the `rocketmq`, but the actual key is not included in the `MessageConst.STRING_HASH_SET`, the real need to add the prefix `RocketMQHeaders.PREFIX`.(Maybe the previous judgment needs to be retained, but it is necessary to add another layer of judgment.)
```java
    public static String toRocketHeaderKey(String rawKey) {
        return RocketMQHeaders.PREFIX + rawKey;
    }
```
refer [spring-cloud-incubator/spring-cloud-alibaba#684](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/684).

**Comment by fangjian0423** [comment]
I wrote a test case about this:

```java
@Test
public void testRocketMQPrefixHeader() {
    org.apache.rocketmq.common.message.Message rmqMsg = new org.apache.rocketmq.common.message.Message();
    rmqMsg.setBody("test body".getBytes());
    rmqMsg.setTags("tags");
    rmqMsg.putUserProperty(RocketMQUtil.toRocketHeaderKey("TAGS"), "tags2");
    Message springMsg = RocketMQUtil.convertToSpringMessage(rmqMsg);
    System.out.println(springMsg.getHeaders().get(RocketMQUtil.toRocketHeaderKey("TAGS")));
}
```

console print: tags2

**Comment by fangjian0423** [comment]
How @walking98  @duhenglucky think about `RocketMQUtil#addUserProperties`?

should we add a `!key.startsWith(RocketMQHeaders.PREFIX)` condition for this?

**Comment by wangxing-git** [comment]
I added this in pr`!MessageConst.STRING_HASH_SET.contains(key.replaceFirst("^" + RocketMQHeaders.PREFIX, "")`.

**Comment by wangxing-git** [comment]
> I added this in pr`!MessageConst.STRING_HASH_SET.contains(key.replaceFirst("^" + RocketMQHeaders.PREFIX, ""))`.

I use two conditions to optimize the number of times the code is executed.
 `!key.startsWith(RocketMQHeaders.PREFIX) || !MessageConst.STRING_HASH_SET.contains(key.replaceFirst("^" + RocketMQHeaders.PREFIX, ""))` 
Reduce the number of executions of `!MessageConst.STRING_HASH_SET.contains(key.replaceFirst("^" + RocketMQHeaders.PREFIX, ""))`

**Comment by vongosling** [comment]
@wangxing-git could you help to add some unit test for your pr.

**Comment by wangxing-git** [comment]
> @wangxing-git could you help to add some unit test for your pr.

I added the relevant unit test.
