### ISSUE TITLE
Message consumption delay is about 30S, I want me to send a message, immediately consume

### ISSUE THREAD

**Issue by jimmycheng888** [apache/rocketmq-spring#91]
Message consumption delay is about 30S, I want me to send a message, immediately consume，
Configuration is the official default configuration, I hope my program can be consumed instantly
my version is 2.3.0

**Comment by ShannonDing** [comment]
Is it the version 2.0.3? the end to end delay should not be in the seconds level. maybe you can test it by sending more messages and have a look at the avg delay.

**Comment by yinjunonly** [comment]
我也是这样，有什么办法解决吗
