### ISSUE TITLE
com.fasterxml.jackson.databind.exc.MismatchedInputException

### ISSUE THREAD

**Issue by stackXu** [apache/rocketmq-spring#94]
官方demo里面OrderPaidEvent这个类,使用了@AllArgsConstructor注解,改注解可能会使jackson反序列化失败,我的lombok版本是1.18.4,改为手写就可以
官方:
![image](https://user-images.githubusercontent.com/35055601/59976392-64f85300-95f6-11e9-9b6d-819a19ef4bb8.png)

![image](https://user-images.githubusercontent.com/35055601/59976350-bfdd7a80-95f5-11e9-8ed1-147ae82e773d.png)

希望将demo改为普通的setget方法,不使用lombok,以免不同lombok版本可能会出现问题
![image](https://user-images.githubusercontent.com/35055601/59976412-8f4a1080-95f6-11e9-8d8f-452b9197acd0.png)

**Comment by vongosling** [comment]
I am quite disgusted with no followup of the problem, please use the latest version to verify whether there is such a problem, and I am very glad to hear your further feedback again.
