### ISSUE TITLE
A component required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found

### ISSUE THREAD

**Issue by h735004790** [apache/rocketmq-spring#98]
springboot2.x and rocketmq-spring-boot-starter2.0.3，when start,
Description:

A component required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'rocketMQTemplate' in 'RocketMQAutoConfiguration' not loaded because @ConditionalOnBean (types: org.apache.rocketmq.client.producer.DefaultMQProducer; SearchStrategy: all) did not find any beans of type org.apache.rocketmq.client.producer.DefaultMQProducer

**Comment by fangjian0423** [comment]
could you please provide a project that reproduces the issue?

**Comment by xue2lang** [comment]
@fangjian0423   when project use Apollo configuration center of XieCheng，project will be started failed，the same problem that：A component required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.

**Comment by fangjian0423** [comment]
I think the configuration items about `rocketmq.name-server` & `rocketmq.producer.group` is not configured in Apollo, so the `RocketMQAutoConfiguration` didn't work.

**Comment by D-Saber** [comment]
> @fangjian0423 when project use Apollo configuration center of XieCheng，project will be started failed，the same problem that：A component required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.



> @fangjian0423 when project use Apollo configuration center of XieCheng，project will be started failed，the same problem that：A component required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.

did you solve it?

**Comment by D-Saber** [comment]
> @fangjian0423 when project use Apollo configuration center of XieCheng，project will be started failed，the same problem that：A component required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.

did you solve it?

**Comment by D-Saber** [comment]
> I think the configuration items about `rocketmq.name-server` & `rocketmq.producer.group` is not configured in Apollo, so the `RocketMQAutoConfiguration` didn't work.

but after packing rocketmq-spring-boot-starter  jar for project  then rocketmq.producer.group is must be configured can be used  I want to know how his loading order is solved.

**Comment by CHN-BinaryLi** [comment]
i also encountered this problem.

**Comment by RongtongJin** [comment]
> i also encountered this problem.

As fangjian0423 said, have you configured items about `rocketmq.name-server` & `rocketmq.producer.group`?

**Comment by fangjian0423** [comment]
Startup with debug mode or see `conditions` endpoint to find why `RocketMQAutoConfiguration` didn't work.

**Comment by vongosling** [comment]
Any update for this issue?

**Comment by ktios** [comment]
i have added rocketmq.name-server and rocketmq.producer.group, but it still can't work .

**Comment by qiankun30** [comment]
解决了吗？

**Comment by liuxuzxx** [comment]
我也出现了这个问题，版本是2.1.0.后来看了下application.yml配置为
```
spring:
    rocketmq:
        name-server: xxxxx
        producer:
            group:xxxxxx
```
看了下RocketMQAutoConfiguration，[笑哭]了，原来配置前缀是prefix="rocketmq"不是prefix="spring.rocketmq"
正确的配置应该是:
```
rocketmq:
  name-server: 172.16.21.138:9876
  producer:
    group: short-message
```

主要是看着datasource,redis,es都是以spring为前缀，也就想当然认为rocketmq也是以spring为大前缀
